For some reason I find it easier to catch these in intellij

diff --git a/.github/workflows/app-misc-jan-appimage-update.yaml b/.github/workflows/app-misc-jan-appimage-update.yaml
--- a/.github/workflows/app-misc-jan-appimage-update.yaml
+++ b/.github/workflows/app-misc-jan-appimage-update.yaml
@@ -74,8 +74,8 @@ jobs:
                 echo 'src_unpack() {'
                 echo '  cp "${DISTDIR}/${A}" "${A}"  || die "Can'\''t copy archive file"'
                 echo '  chmod a+x "${A}"  || die "Can'\''t chmod archive file"'
-                echo "  ./\${A} --appimage-extract ${{env.desktop_file}} || die \"Can't extract .desktop from appimage\""
-                echo "  ./\${A} --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
+                echo "  ./\${A} --appimage-extract ${{env.desktop_file}} || die \"Failed to extract .desktop from appimage\""
+                echo "  ./\${A} --appimage-extract usr/share/icons || die \"Failed to extract icons from app image\""
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
@@ -90,7 +90,7 @@ jobs:
                 echo '  insinto /usr/share/applications'
                 echo '  doins squashfs-root/${{env.desktop_file}} || die "Failed to install desktop file"'
                 echo '  insinto /usr/share/icons'
-                echo '  doins -r squashfs-root/usr/share/icons/hicolor' || die "Failed to install icons"'
+                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
                 echo '}'
                 echo ''
               } > $ebuild_file
