Updated versions

diff --git a/.github/workflows/app-misc-ente-auth-appimage-update.yaml b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
--- a/.github/workflows/app-misc-ente-auth-appimage-update.yaml
+++ b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage todo.config 2024-08-02 15:21:43.522781571 +1000 AEST m=+0.001110369
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
 
 name: app-misc/ente-auth-appimage update
 
@@ -61,7 +61,7 @@ jobs:
           for tag in $tags; do
             version="${tag#auth-v}"
             if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is noauth-v removed skipping"
+                echo "$version == $tag so there is noauth- v removed skipping"
                 continue
             fi
             originalVersion="${version}"
@@ -98,9 +98,9 @@ jobs:
                 echo "    cp \"\${DISTDIR}/\${P}-${{ env.auth_release_name_amd64 }}\" \"${{ env.auth_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.auth_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.auth_appimage_installed_name }} --appimage-extract "${{ env.auth_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.auth_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
-                echo '  ./${{ env.auth_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '  "./${{ env.auth_appimage_installed_name }}" --appimage-extract "${{ env.auth_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.auth_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '  "./${{ env.auth_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
diff --git a/.github/workflows/app-misc-jan-appimage-update.yaml b/.github/workflows/app-misc-jan-appimage-update.yaml
--- a/.github/workflows/app-misc-jan-appimage-update.yaml
+++ b/.github/workflows/app-misc-jan-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage todo.config 2024-08-02 15:40:49.426183246 +1000 AEST m=+0.001124903
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
 
 name: app-misc/jan-appimage update
 
@@ -61,7 +61,7 @@ jobs:
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is nov removed skipping"
+                echo "$version == $tag so there is no v removed skipping"
                 continue
             fi
             originalVersion="${version}"
@@ -97,8 +97,8 @@ jobs:
                 echo "    cp \"\${DISTDIR}/\${P}-${{ env.jan_release_name_amd64 }}\" \"${{ env.jan_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.jan_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.jan_appimage_installed_name }} --appimage-extract "${{ env.jan_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.jan_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '  "./${{ env.jan_appimage_installed_name }}" --appimage-extract "${{ env.jan_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.jan_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
diff --git a/.github/workflows/app-misc-local-ai-appimage-update.yaml b/.github/workflows/app-misc-local-ai-appimage-update.yaml
--- a/.github/workflows/app-misc-local-ai-appimage-update.yaml
+++ b/.github/workflows/app-misc-local-ai-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage todo.config 2024-07-15 23:12:03.136594409 +1000 AEST m=+0.002637113
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
 
 name: app-misc/local-ai-appimage update
 
@@ -61,10 +61,11 @@ jobs:
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is no V removed skipping"
+                echo "$version == $tag so there is no v removed skipping"
                 continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
                 echo "tag / $version doesn't match regexp";
                 continue; 
             fi
@@ -81,7 +82,7 @@ jobs:
                 echo 'KEYWORDS="${{ env.keywords }}"'
                 echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
@@ -96,9 +97,9 @@ jobs:
                 echo "    cp \"\${DISTDIR}/\${P}-${{ env.local-ai_release_name_amd64 }}\" \"${{ env.local-ai_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.local-ai_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.local-ai_appimage_installed_name }} --appimage-extract "${{ env.local-ai_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.local-ai_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
-                echo '  ./${{ env.local-ai_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '  "./${{ env.local-ai_appimage_installed_name }}" --appimage-extract "${{ env.local-ai_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.local-ai_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '  "./${{ env.local-ai_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
@@ -126,7 +127,7 @@ jobs:
               } > $ebuild_file
 
               # Manifest generation
-               
+
               g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/local-ai_${version}_amd64.AppImage" "${{ env.epn }}-${version}-local-ai_${version}_amd64.AppImage" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
diff --git a/.github/workflows/app-misc-maid-appimage-update.yaml b/.github/workflows/app-misc-maid-appimage-update.yaml
--- a/.github/workflows/app-misc-maid-appimage-update.yaml
+++ b/.github/workflows/app-misc-maid-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage input.config 2024-07-15 17:51:33.361709746 +1000 AEST m=+0.001379661
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
 
 name: app-misc/maid-appimage update
 
@@ -60,7 +60,8 @@ jobs:
           tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
           for tag in $tags; do
             version="${tag}"
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
                 echo "tag / $version doesn't match regexp";
                 continue; 
             fi
@@ -77,7 +78,7 @@ jobs:
                 echo 'KEYWORDS="${{ env.keywords }}"'
                 echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
@@ -92,8 +93,8 @@ jobs:
                 echo "    cp \"\${DISTDIR}/\${P}-${{ env.maid_release_name_amd64 }}\" \"${{ env.maid_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.maid_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.maid_appimage_installed_name }} --appimage-extract "${{ env.maid_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.maid_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '  "./${{ env.maid_appimage_installed_name }}" --appimage-extract "${{ env.maid_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.maid_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
@@ -117,7 +118,7 @@ jobs:
               } > $ebuild_file
 
               # Manifest generation
-               
+
               g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/maid.AppImage" "${{ env.epn }}-${version}-maid.AppImage" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
diff --git a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
--- a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
+++ b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
@@ -1,11 +1,13 @@
-name: app-misc/stability-matrix-appimage Update
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
+
+name: app-misc/stability-matrix-appimage update
 
 permissions:
   contents: write
 
 on:
   schedule:
-    - cron: '35 0 * * *'
+    - cron: '18 2 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -22,6 +24,12 @@ env:
   homepage: "https://lykos.ai"
   github_owner: LykosAI
   github_repo: StabilityMatrix
+  keywords: ~amd64
+  workflow_filename: app-misc-stability-matrix-appimage-update.yaml
+  StabilityMatrix_desktop_file: 'zone.lykos.stabilitymatrix.desktop'
+  StabilityMatrix_appimage_installed_name: 'StabilityMatrix.AppImage'
+  StabilityMatrix_appimage_archived_name_amd64: 'StabilityMatrix.AppImage'
+  StabilityMatrix_release_name_amd64: 'StabilityMatrix-linux-x64.zip'
 
 jobs:
   check-and-create-ebuild:
@@ -37,71 +45,79 @@ jobs:
 
       - name: Install required tools
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget jq coreutils unzip
-          url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-          echo "$url"
-          wget "${url}" -O /tmp/g2.deb
-          sudo dpkg -i /tmp/g2.deb
-          rm /tmp/g2.deb
+            sudo apt-get update
+            sudo apt-get install -y wget jq coreutils
+            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+            echo "$url"
+            wget "${url}" -O /tmp/g2.deb
+            sudo dpkg -i /tmp/g2.deb
+            rm /tmp/g2.deb
 
       - name: Process each release
         id: process_releases
         run: |
-          ebuild_dir="./${ecn}/${epn}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-              echo "$version == $tag so there is no V removed skipping"
-              continue
+                echo "$version == $tag so there is no v removed skipping"
+                continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "tag / $version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue; 
             fi
-            ebuild_file="${ebuild_dir}/${epn}-${version}.ebuild"
+            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
+
               {
-                echo "# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/app-misc-stability-matrix-appimage-update.yaml"
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
                 echo 'EAPI=8'
-                echo "DESCRIPTION=\"$description\""
-                echo "HOMEPAGE=\"$homepage\""
+                echo "DESCRIPTION=\"${{ env.description }}\""
+                echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
-                echo 'KEYWORDS="~amd64 ~x86 ~arm ~arm64"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
                 echo "inherit xdg-utils"
                 echo ''
-                echo 'SRC_URI="https://github.com/LykosAI/StabilityMatrix/releases/download/v${PV}/StabilityMatrix-linux-x64.zip -> $P.zip"'
+                echo 'SRC_URI="'
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/StabilityMatrix-linux-x64.zip -> \${P}-StabilityMatrix-linux-x64.zip )"
+                echo '"'
                 echo ''
-                echo "src_unpack() {"
-                echo "  unzip \"\${DISTDIR}/\${A}\" -d \${WORKDIR} || die \"Can't unzip archive file\""
-                echo "  chmod a+x ./StabilityMatrix.AppImage || die \"Can't chmod +x AppImage\""
-                echo "  ./StabilityMatrix.AppImage --appimage-extract zone.lykos.stabilitymatrix.desktop || die \"Can't extract .desktop file from AppImage\""
-                echo "  ./StabilityMatrix.AppImage --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
-                echo "}"
-                echo ""
-                echo "src_prepare() {"
-                echo "  sed -i 's:^Exec=.*:Exec=/usr/bin/StabilityMatrix.AppImage:' squashfs-root/zone.lykos.stabilitymatrix.desktop"
-                echo "  sed -i 's:^TryExec=.*:TryExec=/usr/bin/StabilityMatrix.AppImage:' squashfs-root/zone.lykos.stabilitymatrix.desktop"
-                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
-                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm -v {} \; "
-                echo "  eapply_user"
-                echo "}"
-                echo ""
-                echo "src_install() {"
-                echo '  dobin "${WORKDIR}/StabilityMatrix.AppImage" || die "Failed to install AppImage"'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-StabilityMatrix-linux-x64.zip\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo "    mv \"${{ env.StabilityMatrix_appimage_archived_name_amd64 }}\" \"${{ env.StabilityMatrix_appimage_installed_name }}\"  || die \"Can't move archived file\""
+                echo '  fi'
+                echo '  chmod a+x "${{ env.StabilityMatrix_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  "./${{ env.StabilityMatrix_appimage_installed_name }}" --appimage-extract "${{ env.StabilityMatrix_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.StabilityMatrix_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '}'
+                echo ''
+                echo 'src_prepare() {'
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.StabilityMatrix_appimage_installed_name }}:' 'squashfs-root/${{ env.StabilityMatrix_desktop_file }}'"
+                echo '  eapply_user'
+                echo '}'
+                echo ''
+                echo 'src_install() {'
+                echo '  exeinto /opt/bin'
+                echo '  doexe "${{ env.StabilityMatrix_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins "${WORKDIR}/squashfs-root/zone.lykos.stabilitymatrix.desktop" || die "Failed to install .desktop file"'
-                echo '  insinto /usr/share/icons'
-                echo '  doins -r "${WORKDIR}/squashfs-root/usr/share/icons/hicolor/" || die "Failed to install icons"'
-                echo "}"
+                echo '  doins "squashfs-root/${{ env.StabilityMatrix_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  insinto /usr/share/pixmaps'
+                echo '  doins squashfs-root/*.png || die "Failed to install icons"'
+                echo '}'
                 echo ""
                 echo "pkg_postinst() {"
                 echo "  xdg_desktop_database_update"
@@ -109,17 +125,19 @@ jobs:
                 echo ""
               } > $ebuild_file
 
-              # Generate the manifest for the new ebuild
-              g2 manifest upsert-from-url "https://github.com/LykosAI/StabilityMatrix/releases/download/${tag}/StabilityMatrix-linux-x64.zip" "${epn}-${version}.zip" "${ebuild_dir}/Manifest"
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/StabilityMatrix-linux-x64.zip" "${{ env.epn }}-${version}-StabilityMatrix-linux-x64.zip" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
           done
 
       - name: Commit and push changes
         run: |
-          ebuild_dir="./${ecn}/${epn}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${epn} releases" && 
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag != 0
diff --git a/.github/workflows/app-text-anytype-ts-appimage-update.yaml b/.github/workflows/app-text-anytype-ts-appimage-update.yaml
--- a/.github/workflows/app-text-anytype-ts-appimage-update.yaml
+++ b/.github/workflows/app-text-anytype-ts-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage todo.config 2024-07-24 15:30:24.331266292 +1000 AEST m=+0.001115458
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
 
 name: app-text/anytype-ts-appimage update
 
@@ -61,7 +61,7 @@ jobs:
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-                echo "$version == $tag so there is no V removed skipping"
+                echo "$version == $tag so there is no v removed skipping"
                 continue
             fi
             originalVersion="${version}"
@@ -98,9 +98,9 @@ jobs:
                 echo "    cp \"\${DISTDIR}/\${P}-${{ env.Anytype_release_name_amd64 }}\" \"${{ env.Anytype_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
                 echo '  fi'
                 echo '  chmod a+x "${{ env.Anytype_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                echo '  ./${{ env.Anytype_appimage_installed_name }} --appimage-extract "${{ env.Anytype_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                echo '  ./${{ env.Anytype_appimage_installed_name }} --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
-                echo '  ./${{ env.Anytype_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '  "./${{ env.Anytype_appimage_installed_name }}" --appimage-extract "${{ env.Anytype_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.Anytype_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '  "./${{ env.Anytype_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
diff --git a/.github/workflows/net-misc-localsend-appimage-update.yaml b/.github/workflows/net-misc-localsend-appimage-update.yaml
--- a/.github/workflows/net-misc-localsend-appimage-update.yaml
+++ b/.github/workflows/net-misc-localsend-appimage-update.yaml
@@ -1,3 +1,5 @@
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
+
 name: net-misc/localsend-appimage update
 
 permissions:
@@ -5,7 +7,7 @@ permissions:
 
 on:
   schedule:
-    - cron: '5 1 * * *'
+    - cron: '49 15 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -20,9 +22,13 @@ env:
   epn: localsend-appimage
   description: "An open-source cross-platform alternative to AirDrop"
   homepage: "https://localsend.org"
-  appimage_name: LocalSend.AppImage
   github_owner: localsend
   github_repo: localsend
+  keywords: ~amd64
+  workflow_filename: net-misc-localsend-appimage-update.yaml
+  localsend_desktop_file: 'org.localsend.localsend_app.desktop'
+  localsend_appimage_installed_name: 'localsend.AppImage'
+  localsend_release_name_amd64: 'LocalSend-\${PV}-linux-x86-64.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -38,76 +44,81 @@ jobs:
 
       - name: Install required tools
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget jq coreutils unzip
-          url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-          echo "$url"
-          wget "${url}" -O /tmp/g2.deb
-          sudo dpkg -i /tmp/g2.deb
-          rm /tmp/g2.deb
+            sudo apt-get update
+            sudo apt-get install -y wget jq coreutils
+            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+            echo "$url"
+            wget "${url}" -O /tmp/g2.deb
+            sudo dpkg -i /tmp/g2.deb
+            rm /tmp/g2.deb
 
       - name: Process each release
         id: process_releases
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-              echo "$version == $tag so there is no V removed skipping"
-              continue
+                echo "$version == $tag so there is no v removed skipping"
+                continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "$tag / $version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue; 
             fi
             ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
+
               {
-                echo "# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/"
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
                 echo 'EAPI=8'
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
-                echo 'LICENSE="Unknown"'
+                echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
-                echo 'KEYWORDS="~amd64"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
                 echo "inherit xdg-utils"
                 echo ''
-                echo 'SRC_URI="  '
-                echo '  amd64? ( https://github.com/localsend/localsend/releases/download/v${PV}/LocalSend-${PV}-linux-x86-64.AppImage -> $P.amd64 )'
-                echo '" '
+                echo 'SRC_URI="'
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/LocalSend-\${PV}-linux-x86-64.AppImage -> \${P}-LocalSend-\${PV}-linux-x86-64.AppImage )"
+                echo '"'
                 echo ''
-                echo "src_unpack() {"
-                echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\" || die \"Can't copy archive file\""
-                echo "  chmod a+x \"\${A}\" || die \"Can't chmod archive file\""
-                echo "  ./\${A} --appimage-extract org.localsend.localsend_app.desktop || die \"Can't extract .desktop file from AppImage\""
-                echo "  ./\${A} --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
-                echo "}"
-                echo ""
-                echo "src_prepare() {"
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.appimage_name }}:' squashfs-root/org.localsend.localsend_app.desktop"
-                echo "  sed -i 's:^TryExec=.*:TryExec=/opt/bin/${{ env.appimage_name }}:' squashfs-root/org.localsend.localsend_app.desktop"
-                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
-                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm -v {} \; "
-                echo "  eapply_user"
-                echo "}"
-                echo ""
-                echo "src_install() {"
-                echo '  mv "${WORKDIR}/${P}.amd64" "${WORKDIR}/${{ env.appimage_name }}"'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.localsend_release_name_amd64 }}\" \"${{ env.localsend_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  chmod a+x "${{ env.localsend_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  "./${{ env.localsend_appimage_installed_name }}" --appimage-extract "${{ env.localsend_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.localsend_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '  "./${{ env.localsend_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '}'
+                echo ''
+                echo 'src_prepare() {'
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.localsend_appimage_installed_name }}:' 'squashfs-root/${{ env.localsend_desktop_file }}'"
+                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
+                echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
+                echo '  eapply_user'
+                echo '}'
+                echo ''
+                echo 'src_install() {'
                 echo '  exeinto /opt/bin'
-                echo '  doexe "${WORKDIR}/${{ env.appimage_name }}" || die "Failed to install AppImage"'
-                echo '  dosym /opt/bin/${{ env.appimage_name }} /usr/bin/LocalSend'
+                echo '  doexe "${{ env.localsend_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins "${WORKDIR}/squashfs-root/org.localsend.localsend_app.desktop" || die "Failed to install .desktop file"'
+                echo '  doins "squashfs-root/${{ env.localsend_desktop_file }}" || die "Failed to install desktop file"'
                 echo '  insinto /usr/share/icons'
-                echo '  doins -r "${WORKDIR}/squashfs-root/usr/share/icons/hicolor" || die "Failed to install icons"'
-                echo "}"
+                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
+                echo '  insinto /usr/share/pixmaps'
+                echo '  doins squashfs-root/*.png || die "Failed to install icons"'
+                echo '}'
                 echo ""
                 echo "pkg_postinst() {"
                 echo "  xdg_desktop_database_update"
@@ -115,7 +126,10 @@ jobs:
                 echo ""
               } > $ebuild_file
 
-              g2 manifest upsert-from-url "https://github.com/localsend/localsend/releases/download/${tag}/LocalSend-${version}-linux-x86-64.AppImage" "/tmp/${{ env.epn }}-${version}.amd64" "${ebuild_dir}/Manifest"
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/LocalSend-${version}-linux-x86-64.AppImage" "${{ env.epn }}-${version}-LocalSend-${version}-linux-x86-64.AppImage" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
           done
@@ -124,7 +138,7 @@ jobs:
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${{ env.epn }} releases" && 
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag != 0
diff --git a/.github/workflows/net-misc-rustdesk-appimage-update.yaml b/.github/workflows/net-misc-rustdesk-appimage-update.yaml
--- a/.github/workflows/net-misc-rustdesk-appimage-update.yaml
+++ b/.github/workflows/net-misc-rustdesk-appimage-update.yaml
@@ -1,3 +1,5 @@
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage Release /home/arran/Documents/Projects/arrans_overlay/current.config 2024-08-09 17:52:25.614501782 +1000 AEST m=+0.001349321
+
 name: net-misc/rustdesk-appimage update
 
 permissions:
@@ -5,7 +7,7 @@ permissions:
 
 on:
   schedule:
-    - cron: '15 0 * * *'
+    - cron: '45 14 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -18,10 +20,16 @@ concurrency:
 env:
   ecn: net-misc
   epn: rustdesk-appimage
+  description: "An open-source remote desktop application designed for self-hosting, as an alternative to TeamViewer."
+  homepage: "https://rustdesk.com"
   github_owner: rustdesk
   github_repo: rustdesk
-  description: "An open-source remote desktop, and alternative to TeamViewer."
-  homepage: "https://rustdesk.com/"
+  keywords: ~amd64 ~arm64
+  workflow_filename: net-misc-rustdesk-appimage-update.yaml
+  rustdesk_desktop_file: 'rustdesk.desktop'
+  rustdesk_appimage_installed_name: 'rustdesk.AppImage'
+  rustdesk_release_name_amd64: 'rustdesk-${tag}-x86_64.AppImage'
+  rustdesk_release_name_arm64: 'rustdesk-${tag}-aarch64.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -37,94 +45,100 @@ jobs:
 
       - name: Install required tools
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget jq coreutils
-          url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-          echo "$url"
-          wget "${url}" -O /tmp/g2.deb
-          sudo dpkg -i /tmp/g2.deb
-          rm /tmp/g2.deb
+            sudo apt-get update
+            sudo apt-get install -y wget jq coreutils
+            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+            echo "$url"
+            wget "${url}" -O /tmp/g2.deb
+            sudo dpkg -i /tmp/g2.deb
+            rm /tmp/g2.deb
 
       - name: Process each release
         id: process_releases
         run: |
-          ghrp=${{env.github_owner}}/${{env.github_repo}}
-          ebuild_dir="./${ecn}/${epn}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
           for tag in $tags; do
             version="${tag}"
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "$tag / $version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)[0-9]*\)$/\1_\5\3/')"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue; 
             fi
-            ebuild_file="${ebuild_dir}/${epn}-${version}.ebuild"
+            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
-              
-              # Create ebuild script
+
               {
-                echo "# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/net-misc-rustdesk-appimage-update.yaml"
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
                 echo 'EAPI=8'
-                echo "DESCRIPTION=\"$description\""
-                echo "HOMEPAGE=\"https://github.com/${ghrp}\""
+                echo "DESCRIPTION=\"${{ env.description }}\""
+                echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
-                echo 'KEYWORDS="~amd64 ~arm64"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/glibc sys-libs/zlib sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
                 echo "inherit xdg-utils"
                 echo ''
-                echo 'SRC_URI="  '
-                echo "  amd64? ( https://github.com/${ghrp}/releases/download/\${PV}/rustdesk-\${PV}-x86_64.AppImage -> \$P.amd64 )"
-                echo "  arm64? ( https://github.com/${ghrp}/releases/download/\${PV}/rustdesk-\${PV}-aarch64.AppImage -> \$P.arm64 )"
-                echo '" '
+                echo 'SRC_URI="'
+                echo "  arm64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rustdesk-${tag}-aarch64.AppImage -> \${P}-rustdesk-${tag}-aarch64.AppImage )"
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rustdesk-${tag}-x86_64.AppImage -> \${P}-rustdesk-${tag}-x86_64.AppImage )"
+                echo '"'
                 echo ''
-                echo "src_unpack() {"
-                echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\"  || die \"Can't copy archive file\""
-                echo "  chmod a+x \"\${A}\"  || die \"Can't chmod archive file\""
-                echo "  \"./\${A}\" --appimage-extract rustdesk.desktop || die \"Can't extract .desktop from appimage\""
-                echo "  \"./\${A}\" --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
-                echo "}"
-                echo ""
-                echo "src_prepare() {"
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/rustdesk:' squashfs-root/rustdesk.desktop"
-                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.rustdesk_release_name_amd64 }}\" \"${{ env.rustdesk_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.rustdesk_release_name_arm64 }}\" \"${{ env.rustdesk_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  chmod a+x "${{ env.rustdesk_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  "./${{ env.rustdesk_appimage_installed_name }}" --appimage-extract "${{ env.rustdesk_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.rustdesk_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '}'
+                echo ''
+                echo 'src_prepare() {'
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.rustdesk_appimage_installed_name }}:' 'squashfs-root/${{ env.rustdesk_desktop_file }}'"
                 echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
-                echo "  eapply_user"
-                echo "}"
-                echo ""
+                echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
+                echo '  eapply_user'
+                echo '}'
+                echo ''
                 echo 'src_install() {'
-                echo '  mv -v "${DISTDIR}/${A}" rustdesk'
                 echo '  exeinto /opt/bin'
-                echo '  doexe "rustdesk"'
+                echo '  doexe "${{ env.rustdesk_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins "./squashfs-root/rustdesk.desktop"'
-                echo '  insinto /usr/share/'
-                echo '  doins -r "./squashfs-root/usr/share/icons"'
-                echo "}"
+                echo '  doins "squashfs-root/${{ env.rustdesk_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  insinto /usr/share/icons'
+                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
+                echo '}'
                 echo ""
                 echo "pkg_postinst() {"
                 echo "  xdg_desktop_database_update"
                 echo "}"
                 echo ""
-              } > "$ebuild_file"
+              } > $ebuild_file
 
-              # Generate the manifest for the new ebuild
-              g2 manifest upsert-from-url "https://github.com/${ghrp}/releases/download/${tag}/rustdesk-${version}-x86_64.AppImage" "${epn}-${version}.amd64" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${ghrp}/releases/download/${tag}/rustdesk-${version}-aarch64.AppImage" "${epn}-${version}.arm64" "${ebuild_dir}/Manifest"
-              
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rustdesk-${tag}-aarch64.AppImage" "${{ env.epn }}-${version}-rustdesk-${tag}-aarch64.AppImage" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rustdesk-${tag}-x86_64.AppImage" "${{ env.epn }}-${version}-rustdesk-${tag}-x86_64.AppImage" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
           done
 
       - name: Commit and push changes
         run: |
-          ebuild_dir="./${ecn}/${epn}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${epn} releases" && 
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag != 0
