Jan fixes.

diff --git a/.github/workflows/app-misc-jan-appimage-update.yaml b/.github/workflows/app-misc-jan-appimage-update.yaml
--- a/.github/workflows/app-misc-jan-appimage-update.yaml
+++ b/.github/workflows/app-misc-jan-appimage-update.yaml
@@ -69,7 +69,7 @@ jobs:
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
-                echo 'SRC_URI="https://github.com//${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v${PV}/jan-linux-x86_64-${PV}.AppImage -> ${P}.AppImage"'
+                echo 'SRC_URI="https://github.com//${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v${PV}/jan-linux-x86_64-${PV}.AppImage -> ${P}.amd64"'
                 echo ''
                 echo 'src_unpack() {'
                 echo '  cp "${DISTDIR}/${A}" "${A}"  || die "Can'\''t copy archive file"'
@@ -84,13 +84,13 @@ jobs:
                 echo '}'
                 echo ''
                 echo 'src_install() {'
-                echo '  mv "${P}.amd64" "${{ env.appimage_installed_name }}"'
+                echo '  mv "${P}.amd64" "${{ env.appimage_installed_name }}" || die "Failed to rename AppImage"'
                 echo '  exeinto /opt/bin'
                 echo '  doexe "${{ env.appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins squashfs-root/${{env.desktop_file}}'
+                echo '  doins squashfs-root/${{env.desktop_file}} || die "Failed to install desktop file"'
                 echo '  insinto /usr/share/icons'
-                echo '  doins -r squashfs-root/usr/share/icons/hicolor'
+                echo '  doins -r squashfs-root/usr/share/icons/hicolor' || die "Failed to install icons"'
                 echo '}'
                 echo ''
               } > $ebuild_file
