Update app-misc-stability-matrix-appimage-update.yaml

diff --git a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
--- a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
+++ b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
@@ -79,8 +79,8 @@ jobs:
                 echo '  dobin "${WORKDIR}/StabilityMatrix.AppImage" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
                 echo '  doins "${WORKDIR}/squashfs-root/zone.lykos.stabilitymatrix.desktop" || die "Failed to install .desktop file"'
-                echo '  insinto /usr/share/icons/hicolor'
-                echo '  doins -r "${WORKDIR}/squashfs-root/usr/share/icons" || die "Failed to install icons"'
+                echo '  insinto /usr/share/icons'
+                echo '  doins -r "${WORKDIR}/squashfs-root/usr/share/icons/hicolor/" || die "Failed to install icons"'
                 echo "}"
                 echo ""
                 echo "pkg_postinst() {"
