Fixes.

diff --git a/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml b/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
--- a/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
+++ b/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
@@ -109,8 +109,8 @@ jobs:
                     condition="${variant}"
                   fi
                   echo "    if use $condition; then"
-                  echo "      mv \"$mvafn\" '$mvfn' || die 'failed to move $mvfn'"
-                  echo "      chmod +x '$mvfn' || die 'failed to chmod $mvfn'"
+                  echo "      cp \"${DISTDIR}/${mvafn}\" '$mvfn' || die 'failed to move $mvfn'"
+                  echo "      chmod +x '${mvfn}' || die 'failed to chmod $mvfn'"
                   echo "    fi"
                 done
                 echo "}"
