Jan updated. Somehow missed it.

diff --git a/.github/workflows/app-misc-jan-appimage-update.yaml b/.github/workflows/app-misc-jan-appimage-update.yaml
--- a/.github/workflows/app-misc-jan-appimage-update.yaml
+++ b/.github/workflows/app-misc-jan-appimage-update.yaml
@@ -1,3 +1,5 @@
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github AppImage todo.config 2024-08-02 15:40:49.426183246 +1000 AEST m=+0.001124903
+
 name: app-misc/jan-appimage update
 
 permissions:
@@ -5,7 +7,7 @@ permissions:
 
 on:
   schedule:
-    - cron: '15 1 * * *'
+    - cron: '13 5 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -20,10 +22,13 @@ env:
   epn: jan-appimage
   description: "Jan is an open source alternative to ChatGPT that runs 100% offline on your computer. Multiple engine support (llama.cpp, TensorRT-LLM)"
   homepage: "https://jan.ai/"
-  desktop_file: "jan.desktop"
-  appimage_installed_name: jan.AppImage
-  github_owner: "janhq"
-  github_repo: "jan"
+  github_owner: janhq
+  github_repo: jan
+  keywords: ~amd64
+  workflow_filename: app-misc-jan-appimage-update.yaml
+  jan_desktop_file: 'jan.desktop'
+  jan_appimage_installed_name: 'jan.AppImage'
+  jan_release_name_amd64: 'jan-linux-x86_64-\${PV}.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -39,74 +44,75 @@ jobs:
 
       - name: Install required tools
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget jq coreutils tar
-          url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-          echo "$url"
-          wget "${url}" -O /tmp/g2.deb
-          sudo dpkg -i /tmp/g2.deb
-          rm /tmp/g2.deb
+            sudo apt-get update
+            sudo apt-get install -y wget jq coreutils
+            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+            echo "$url"
+            wget "${url}" -O /tmp/g2.deb
+            sudo dpkg -i /tmp/g2.deb
+            rm /tmp/g2.deb
 
       - name: Process each release
         id: process_releases
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
-          
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
           for tag in $tags; do
             version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-              echo "$version == $tag so there is no V removed skipping"
-              continue
+                echo "$version == $tag so there is nov removed skipping"
+                continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "tag / $version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue; 
             fi
             ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
-              
-              # Create ebuild script
+
               {
-                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/app-misc-jan-appimage-update.yaml'
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
                 echo 'EAPI=8'
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
-                echo 'KEYWORDS="~amd64"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
                 echo 'IUSE=""'
                 echo 'DEPEND=""'
-                echo 'RDEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
                 echo "inherit xdg-utils"
                 echo ''
-                echo 'SRC_URI="https://github.com//${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v${PV}/jan-linux-x86_64-${PV}.AppImage -> ${P}.amd64"'
+                echo 'SRC_URI="'
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/jan-linux-x86_64-\${PV}.AppImage -> \${P}-jan-linux-x86_64-\${PV}.AppImage )"
+                echo '"'
                 echo ''
                 echo 'src_unpack() {'
-                echo '  cp "${DISTDIR}/${A}" "${A}"  || die "Can'\''t copy archive file"'
-                echo '  chmod a+x "${A}"  || die "Can'\''t chmod archive file"'
-                echo "  ./\${A} --appimage-extract ${{env.desktop_file}} || die \"Failed to extract .desktop from appimage\""
-                echo "  ./\${A} --appimage-extract usr/share/icons || die \"Failed to extract icons from app image\""
+                echo '  if use amd64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.jan_release_name_amd64 }}\" \"${{ env.jan_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  chmod a+x "${{ env.jan_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  ./${{ env.jan_appimage_installed_name }} --appimage-extract "${{ env.jan_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  ./${{ env.jan_appimage_installed_name }} --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.appimage_installed_name }}:' squashfs-root/${{env.desktop_file}}"
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.jan_appimage_installed_name }}:' 'squashfs-root/${{ env.jan_desktop_file }}'"
                 echo '  eapply_user'
                 echo '}'
                 echo ''
                 echo 'src_install() {'
-                echo '  mv "${P}.amd64" "${{ env.appimage_installed_name }}" || die "Failed to rename AppImage"'
                 echo '  exeinto /opt/bin'
-                echo '  doexe "${{ env.appimage_installed_name }}" || die "Failed to install AppImage"'
+                echo '  doexe "${{ env.jan_appimage_installed_name }}" || die "Failed to install AppImage"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins squashfs-root/${{env.desktop_file}} || die "Failed to install desktop file"'
-                echo '  insinto /usr/share/icons'
-                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
+                echo '  doins "squashfs-root/${{ env.jan_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  insinto /usr/share/pixmaps'
+                echo '  doins squashfs-root/*.png || die "Failed to install icons"'
                 echo '}'
                 echo ""
                 echo "pkg_postinst() {"
@@ -115,8 +121,10 @@ jobs:
                 echo ""
               } > $ebuild_file
 
-              # Generate the manifest for the new ebuild
-              g2 manifest upsert-from-url "https://github.com//${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/jan-linux-x86_64-${version}.AppImage" "${{ env.epn }}-${version}.amd64" "${ebuild_dir}/Manifest"
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/jan-linux-x86_64-${version}.AppImage" "${{ env.epn }}-${version}-jan-linux-x86_64-${version}.AppImage" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
             break
           done
@@ -125,7 +133,7 @@ jobs:
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           git add ./${ebuild_dir}
-          git commit -m "Add ebuilds for new ${{ env.epn }} releases" && 
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag != 0
