Simple icon dir clean up & some desktop fix

diff --git a/.github/workflows/app-misc-flutter_google_datastore-appimage-update.yaml b/.github/workflows/app-misc-flutter_google_datastore-appimage-update.yaml
--- a/.github/workflows/app-misc-flutter_google_datastore-appimage-update.yaml
+++ b/.github/workflows/app-misc-flutter_google_datastore-appimage-update.yaml
@@ -68,13 +68,15 @@ jobs:
                 echo "src_unpack() {"
                 echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\" || die \"Can't copy archive file\""
                 echo "  chmod a+x \"\${A}\" || die \"Can't chmod archive file\""
-                echo "  ./\${A} --appimage-extract \*.desktop || die \"Can't extract .desktop file from AppImage\""
+                echo "  ./\${A} --appimage-extract flutter_google_datastore.desktop || die \"Can't extract .desktop file from AppImage\""
                 echo "  ./\${A} --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
                 echo "}"
                 echo ""
                 echo "src_prepare() {"
                 echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.appimage_name }}:' squashfs-root/flutter_google_datastore.desktop"
                 echo "  sed -i 's:^TryExec=.*:TryExec=/opt/bin/${{ env.appimage_name }}:' squashfs-root/flutter_google_datastore.desktop"
+                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
+                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm -v {} \; "
                 echo "  eapply_user"
                 echo "}"
                 echo ""
diff --git a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
--- a/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
+++ b/.github/workflows/app-misc-stability-matrix-appimage-update.yaml
@@ -65,13 +65,15 @@ jobs:
                 echo "src_unpack() {"
                 echo "  unzip \"\${DISTDIR}/\${A}\" -d \${WORKDIR} || die \"Can't unzip archive file\""
                 echo "  chmox a+x ./StabilityMatrix.AppImage || die \"Can't chmod +x AppImage\""
-                echo "  ./StabilityMatrix.AppImage --appimage-extract \*.desktop || die \"Can't extract .desktop file from AppImage\""
+                echo "  ./StabilityMatrix.AppImage --appimage-extract zone.lykos.stabilitymatrix.desktop || die \"Can't extract .desktop file from AppImage\""
                 echo "  ./StabilityMatrix.AppImage --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
                 echo "}"
                 echo ""
                 echo "src_prepare() {"
                 echo "  sed -i 's:^Exec=.*:Exec=/usr/bin/StabilityMatrix.AppImage:' squashfs-root/zone.lykos.stabilitymatrix.desktop"
                 echo "  sed -i 's:^TryExec=.*:TryExec=/usr/bin/StabilityMatrix.AppImage:' squashfs-root/zone.lykos.stabilitymatrix.desktop"
+                echo "  find squashfs-root -type d -exec rmdir -p {} \; "
+                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm -v {} \; "
                 echo "  eapply_user"
                 echo "}"
                 echo ""
