feat: Add md2png to config and generate workflows
This change adds the `md2png` application to the `current.config` file and generates the corresponding GitHub Actions workflow.

The workflow has been regenerated with the latest version of the `overlay_workflow_builder_generator` (v0.1.22), which correctly prefers the `.tar.gz` assets.

diff --git a/.github/workflows/app-text-md2png-bin-update.yaml b/.github/workflows/app-text-md2png-bin-update.yaml
--- a/.github/workflows/app-text-md2png-bin-update.yaml
+++ b/.github/workflows/app-text-md2png-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.22 Github Binary Release current.config 2026-01-10 03:09:50.386499191 +0000 UTC m=+0.004991240
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.22 Github Binary Release current.config 2026-01-10 03:33:27.755759153 +0000 UTC m=+0.020988087
 
 name: app-text/md2png-bin update
 
@@ -24,13 +24,15 @@ env:
   homepage: "https://github.com/arran4/md2png"
   github_owner: arran4
   github_repo: md2png
-  keywords: ~amd64 ~x86
+  keywords: ~amd64 ~arm ~arm64
   workflow_filename: app-text-md2png-bin-update.yaml
   md2png_binary_installed_name: 'md2png'
-  md2png_binary_archived_name_amd64: './usr/bin/md2png'
-  md2png_release_name_amd64: 'md2png_\${PV}_linux_amd64.deb'
-  md2png_binary_archived_name_x86: './usr/bin/md2png'
-  md2png_release_name_x86: 'md2png_\${PV}_linux_386.deb'
+  md2png_binary_archived_name_amd64: 'md2png'
+  md2png_release_name_amd64: 'md2png_\${PV}_Linux_x86_64.tar.gz'
+  md2png_binary_archived_name_arm: 'md2png'
+  md2png_release_name_arm: 'md2png_\${PV}_Linux_armv7.tar.gz'
+  md2png_binary_archived_name_arm64: 'md2png'
+  md2png_release_name_arm64: 'md2png_\${PV}_Linux_arm64.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -104,8 +106,9 @@ EOF
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
-                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_linux_amd64.deb -> \${P}-md2png_\${PV}_linux_amd64.deb  )  "
-                echo "	x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_linux_386.deb -> \${P}-md2png_\${PV}_linux_386.deb  )  "
+                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_Linux_x86_64.tar.gz -> \${P}-md2png_\${PV}_Linux_x86_64.tar.gz  )  "
+                echo "	arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_Linux_armv7.tar.gz -> \${P}-md2png_\${PV}_Linux_armv7.tar.gz  )  "
+                echo "	arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_Linux_arm64.tar.gz -> \${P}-md2png_\${PV}_Linux_arm64.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -130,10 +133,13 @@ EOF
                 echo ''
                 echo 'src_unpack() {'
                 echo '  if use amd64; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_linux_amd64.deb\" || die \"Can't unpack archive file\""
+                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
                 echo '  fi'
-                echo '  if use x86; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_linux_386.deb\" || die \"Can't unpack archive file\""
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_armv7.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
                 echo '  fi'
                 echo '}'
                 echo ''
@@ -142,16 +148,20 @@ EOF
                 echo '  if use amd64; then'
                 echo '    newexe "${{ env.md2png_binary_archived_name_amd64 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
-                echo '  if use x86; then'
-                echo '    newexe "${{ env.md2png_binary_archived_name_x86 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.md2png_binary_archived_name_arm }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.md2png_binary_archived_name_arm64 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_linux_amd64.deb" "${{ env.epn }}-${version}-md2png_${version}_linux_amd64.deb" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_linux_386.deb" "${{ env.epn }}-${version}-md2png_${version}_linux_386.deb" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_armv7.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_armv7.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
