Lemmy updated to include app image.

diff --git a/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml b/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
--- a/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
+++ b/.github/workflows/app-misc-lemmy-notify-appimage-update.yaml
@@ -5,7 +5,7 @@ permissions:
 
 on:
   schedule:
-    - cron: '55 0 * * *'
+    - cron: '5 0 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -13,10 +13,10 @@ on:
 
 env:
   ecn: app-misc
-  epn: lemmy-notify
+  epn: lemmy-notify-appimage
   description: "Lemmy Notification app - for desktop atm"
   homepage: "https://github.com/arran4/lemmy_notify"
-  appimage_name: LemmyNotify.AppImage
+  appimage_name: lemmy_notify.AppImage
 
 jobs:
   check-and-create-ebuild:
@@ -53,7 +53,7 @@ jobs:
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
-                echo 'KEYWORDS="~amd64 ~arm64"'
+                echo 'KEYWORDS="~amd64"'
                 echo 'DEPEND=""'
                 echo 'RDEPEND=""'
                 echo 'S="${WORKDIR}"'
@@ -61,15 +61,13 @@ jobs:
                 echo ''
                 echo "inherit xdg-utils"
                 echo ''
-                echo 'SRC_URI="  '
-                echo '  amd64? ( https://github.com/arran4/lemmy_notify/releases/download/v${PV}/lemmy_notify-${PV}-linux-x86_64.AppImage -> $P.amd64 )'
-                echo '" '
+                echo 'SRC_URI="https://github.com/arran4/lemmy_notify/releases/download/${PV}/lemmy_notify-linux-x86_64.AppImage -> $P.AppImage"'
                 echo ''
                 echo "src_unpack() {"
                 echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\" || die \"Can't copy archive file\""
                 echo "  chmod a+x \"\${A}\" || die \"Can't chmod archive file\""
-                echo "  ./\${A} --appimage-extract \*.desktop || die \"Can't extract .desktop file from AppImage\""
-                echo "  ./\${A} --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
+                echo "  ./${A} --appimage-extract \*.desktop || die \"Can't extract .desktop file from AppImage\""
+                echo "  ./${A} --appimage-extract usr/share/icons || die \"Can't extract icons from AppImage\""
                 echo "}"
                 echo ""
                 echo "src_prepare() {"
@@ -79,10 +77,10 @@ jobs:
                 echo "}"
                 echo ""
                 echo "src_install() {"
-                echo '  mv "${WORKDIR}/${P}.amd64" "${WORKDIR}/${{ env.appimage_name }}"'
+                echo '  mv "${WORKDIR}/${P}.AppImage" "${WORKDIR}/${{ env.appimage_name }}"'
                 echo '  exeinto /opt/bin'
                 echo '  doexe "${WORKDIR}/${{ env.appimage_name }}" || die "Failed to install AppImage"'
-                echo '  dosym /opt/bin/${{ env.appimage_name }} /usr/bin/LemmyNotify'
+                echo '  dosym /opt/bin/${{ env.appimage_name }} /usr/bin/lemmy-notify'
                 echo '  insinto /usr/share/applications'
                 echo '  doins "${WORKDIR}/squashfs-root/*.desktop" || die "Failed to install .desktop file"'
                 echo '  insinto /usr/share/icons/hicolor'
@@ -96,11 +94,11 @@ jobs:
               } > $ebuild_file
 
               # Generate the manifest for the new ebuild
-              wget https://github.com/arran4/lemmy_notify/releases/download/${latest_release}/lemmy_notify-${version}-linux-x86_64.AppImage -O /tmp/${{ env.epn }}-${version}.amd64
+              wget https://github.com/arran4/lemmy_notify/releases/download/${latest_release}/lemmy_notify-linux-x86_64.AppImage -O /tmp/${{ env.epn }}-${version}.AppImage
               
-              echo "DIST ${{ env.epn }}-${version}.amd64 $(stat -c %s "/tmp/${{ env.epn }}-${version}.amd64") BLAKE2B $(b2sum "/tmp/${{ env.epn }}-${version}.amd64" | cut -d' ' -f1) SHA512 $(sha512sum "/tmp/${{ env.epn }}-${version}.amd64" | cut -d' ' -f1)" | tee -a "${ebuild_dir}/Manifest"
-              
-              rm "/tmp/${{ env.epn }}-${version}.amd64"
+              e="${{ env.epn }}-${version}.AppImage"
+              echo "DIST $e $(stat -c %s "/tmp/${e}") BLAKE2B $(b2sum "/tmp/${e}" | cut -d' ' -f1) SHA512 $(sha512sum "/tmp/${e}" | cut -d' ' -f1)" | tee -a "${ebuild_dir}/Manifest"
+              rm "/tmp/${e}"
           fi
 
       - name: Commit and push changes
