feat: Add md2png to config and generate workflows
This change adds the `md2png` application to the `current.config` file and generates the corresponding GitHub Actions workflow. The configuration has been updated to use the `.deb` packages from the latest release, as the `tar.gz` files are no longer available for Linux.

diff --git a/.github/workflows/app-text-md2png-bin-update.yaml b/.github/workflows/app-text-md2png-bin-update.yaml
--- a/.github/workflows/app-text-md2png-bin-update.yaml
+++ b/.github/workflows/app-text-md2png-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.18 Github Binary Release current.config 2025-10-15 07:28:23.840233983 +0000 UTC m=+0.011253403
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.21 Github Binary Release current.config 2026-01-10 02:05:40.206628108 +0000 UTC m=+0.005703791
 
 name: app-text/md2png-bin update
 
@@ -24,15 +24,13 @@ env:
   homepage: "https://github.com/arran4/md2png"
   github_owner: arran4
   github_repo: md2png
-  keywords: ~amd64 ~arm ~arm64
+  keywords: ~amd64 ~x86
   workflow_filename: app-text-md2png-bin-update.yaml
   md2png_binary_installed_name: 'md2png'
-  md2png_binary_archived_name_amd64: 'md2png'
-  md2png_release_name_amd64: 'md2png_\${PV}_Linux_x86_64.tar.gz'
-  md2png_binary_archived_name_arm: 'md2png'
-  md2png_release_name_arm: 'md2png_\${PV}_Linux_armv7.tar.gz'
-  md2png_binary_archived_name_arm64: 'md2png'
-  md2png_release_name_arm64: 'md2png_\${PV}_Linux_arm64.tar.gz'
+  md2png_binary_archived_name_amd64: './usr/bin/md2png'
+  md2png_release_name_amd64: 'md2png_\${PV}_linux_amd64.deb'
+  md2png_binary_archived_name_x86: './usr/bin/md2png'
+  md2png_release_name_x86: 'md2png_\${PV}_linux_386.deb'
 
 jobs:
   check-and-create-ebuild:
@@ -61,6 +59,18 @@ jobs:
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
+          metadata_file="${ebuild_dir}/metadata.xml"
+          if [ ! -f "$metadata_file" ]; then
+            cat <<EOF > "$metadata_file"
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
+<pkgmetadata>
+	<upstream>
+		<remote-id type="github">arran4/md2png</remote-id>
+	</upstream>
+</pkgmetadata>
+EOF
+          fi
           declare -A releaseTypes=()
           tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
           for tag in $tags; do
@@ -93,31 +103,37 @@ jobs:
                 echo 'EAPI=8'
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
+                echo 'SRC_URI="'
+                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_linux_amd64.deb -> \${P}-md2png_\${PV}_linux_amd64.deb  )  "
+                echo "	x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/md2png_\${PV}_linux_386.deb -> \${P}-md2png_\${PV}_linux_386.deb  )  "
+                echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
                 echo 'KEYWORDS="${{ env.keywords }}"'
-                echo 'IUSE=""'
-                echo 'REQUIRED_USE=""'
-                echo 'DEPEND=""'
-                echo 'RDEPEND="sys-libs/glibc "'
-                echo 'S="${WORKDIR}"'
-                echo ''
-                echo ''
-                echo 'SRC_URI="'
-                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_\${PV}_Linux_x86_64.tar.gz -> \${P}-md2png_\${PV}_Linux_x86_64.tar.gz  )  "
-                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_\${PV}_Linux_armv7.tar.gz -> \${P}-md2png_\${PV}_Linux_armv7.tar.gz  )  "
-                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_\${PV}_Linux_arm64.tar.gz -> \${P}-md2png_\${PV}_Linux_arm64.tar.gz  )  "
+                echo -n 'IUSE="'
+                echo -n ''
+                echo -n ''
+                echo -n ''
+                echo -n ''
                 echo '"'
+                echo ''
+                echo -n 'REQUIRED_USE="'
+                echo -n ''
+                echo '"'
+                echo ''
+                echo -n 'RDEPEND="'
+                echo -n ''
+                echo -n ''
+                echo '"'
+                echo ''
+                echo 'S="${WORKDIR}"'
                 echo ''
                 echo 'src_unpack() {'
                 echo '  if use amd64; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
+                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_linux_amd64.deb\" || die \"Can't unpack archive file\""
                 echo '  fi'
-                echo '  if use arm; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_armv7.tar.gz\" || die \"Can't unpack archive file\""
-                echo '  fi'
-                echo '  if use arm64; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-md2png_\${PV}_linux_386.deb\" || die \"Can't unpack archive file\""
                 echo '  fi'
                 echo '}'
                 echo ''
@@ -126,21 +142,16 @@ jobs:
                 echo '  if use amd64; then'
                 echo '    newexe "${{ env.md2png_binary_archived_name_amd64 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
-                echo '  if use arm; then'
-                echo '    newexe "${{ env.md2png_binary_archived_name_arm }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
-                echo '  fi'
-                echo '  if use arm64; then'
-                echo '    newexe "${{ env.md2png_binary_archived_name_arm64 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.md2png_binary_archived_name_x86 }}" "${{ env.md2png_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '}'
-                echo ""
               } > $ebuild_file
 
               # Manifest generation
 
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_armv7.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_armv7.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-md2png_${version}_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_linux_amd64.deb" "${{ env.epn }}-${version}-md2png_${version}_linux_amd64.deb" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/md2png_${version}_linux_386.deb" "${{ env.epn }}-${version}-md2png_${version}_linux_386.deb" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
