[DO NOT MERGE] Fix htmlq and g2 installation paths
This commit resolves GitHub Actions CI failures caused by the `Unable to locate package htmlq` apt-get error and the `package github.com/arran4/g2 is not a main package` Go installation error.

* The `.deb` fallback is kept, but `htmlq` is explicitly downloaded and extracted to `/usr/local/bin/htmlq` since it's not available in the default Ubuntu 24.04 repositories.
* The Go path is updated from `github.com/arran4/g2@latest` to `github.com/arran4/g2/cmd/g2@latest`, and `~/go/bin/g2` is copied to `/usr/local/bin/` so it's globally available for the CI runner.

diff --git a/.github/workflows/app-admin-chezmoi-bin-update.yaml b/.github/workflows/app-admin-chezmoi-bin-update.yaml
--- a/.github/workflows/app-admin-chezmoi-bin-update.yaml
+++ b/.github/workflows/app-admin-chezmoi-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: app-admin/chezmoi-bin update
 
@@ -24,10 +24,35 @@ env:
   homepage: "https://www.chezmoi.io/"
   github_owner: twpayne
   github_repo: chezmoi
-  keywords:
+  keywords: ~amd64 ~arm ~arm64 ~ppc64 ~riscv ~s390 ~x86
   workflow_filename: app-admin-chezmoi-bin-update.yaml
-  chezmoi_binary_installed_name: ''
-  glibc_binary_installed_name: ''
+  android_binary_installed_name: 'chezmoi'
+  android_binary_archived_name_arm64: 'chezmoi'
+  android_release_name_arm64: 'chezmoi_\${PV}_android_arm64.tar.gz'
+  chezmoi_binary_installed_name: 'chezmoi'
+  chezmoi_binary_archived_name_amd64: 'chezmoi'
+  chezmoi_release_name_amd64: 'chezmoi_\${PV}_linux-musl_amd64.tar.gz'
+  chezmoi_binary_archived_name_arm: 'chezmoi'
+  chezmoi_release_name_arm: 'chezmoi_\${PV}_linux_arm.tar.gz'
+  chezmoi_binary_archived_name_arm64: 'chezmoi'
+  chezmoi_release_name_arm64: 'chezmoi_\${PV}_linux_arm64.tar.gz'
+  chezmoi_binary_archived_name_ppc64: 'chezmoi'
+  chezmoi_release_name_ppc64: 'chezmoi_\${PV}_linux_ppc64.tar.gz'
+  chezmoi_binary_archived_name_riscv: 'chezmoi'
+  chezmoi_release_name_riscv: 'chezmoi_\${PV}_linux_riscv64.tar.gz'
+  chezmoi_binary_archived_name_s390: 'chezmoi'
+  chezmoi_release_name_s390: 'chezmoi_\${PV}_linux_s390x.tar.gz'
+  chezmoi_binary_archived_name_x86: 'chezmoi'
+  chezmoi_release_name_x86: 'chezmoi_\${PV}_linux_i386.tar.gz'
+  glibc_binary_installed_name: 'chezmoi'
+  glibc_binary_archived_name_amd64: 'chezmoi'
+  glibc_release_name_amd64: 'chezmoi_\${PV}_linux-glibc_amd64.tar.gz'
+  le_binary_installed_name: 'chezmoi'
+  le_binary_archived_name_ppc64: 'chezmoi'
+  le_release_name_ppc64: 'chezmoi_\${PV}_linux_ppc64le.tar.gz'
+  loong64_binary_installed_name: 'chezmoi'
+  loong64_binary_archived_name_amd64: 'chezmoi'
+  loong64_release_name_amd64: 'chezmoi_\${PV}_linux_loong64.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -47,7 +72,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -63,16 +89,16 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
-              <use>
-                <flag name="android">Install android binary</flag>
-                <flag name="glibc">Install glibc binary</flag>
-                <flag name="le">Install le binary</flag>
-                <flag name="loong64">Install loong64 binary</flag>
-              </use>
+            <use>
+              <flag name="android">Install android binary</flag>
+              <flag name="glibc">Install glibc binary</flag>
+              <flag name="le">Install le binary</flag>
+              <flag name="loong64">Install loong64 binary</flag>
+            </use>
             <upstream>
               <remote-id type="github">twpayne/chezmoi</remote-id>
             </upstream>
@@ -115,6 +141,17 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? ( glibc? ( !loong64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux-glibc_amd64.tar.gz -> \${P}-chezmoi_\${PV}_linux-glibc_amd64.tar.gz  )  )  )  "
+                echo "  amd64? ( !glibc? ( !loong64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux-musl_amd64.tar.gz -> \${P}-chezmoi_\${PV}_linux-musl_amd64.tar.gz  )  )  )  "
+                echo "  amd64? ( loong64? ( !glibc? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_loong64.tar.gz -> \${P}-chezmoi_\${PV}_linux_loong64.tar.gz  )  )  )  "
+                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_arm.tar.gz -> \${P}-chezmoi_\${PV}_linux_arm.tar.gz  )  "
+                echo "  arm64? ( android? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_android_arm64.tar.gz -> \${P}-chezmoi_\${PV}_android_arm64.tar.gz  )  )  "
+                echo "  arm64? ( !android? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_arm64.tar.gz -> \${P}-chezmoi_\${PV}_linux_arm64.tar.gz  )  )  "
+                echo "  ppc64? ( !le? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_ppc64.tar.gz -> \${P}-chezmoi_\${PV}_linux_ppc64.tar.gz  )  )  "
+                echo "  ppc64? ( le? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_ppc64le.tar.gz -> \${P}-chezmoi_\${PV}_linux_ppc64le.tar.gz  )  )  "
+                echo "  riscv? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_riscv64.tar.gz -> \${P}-chezmoi_\${PV}_linux_riscv64.tar.gz  )  "
+                echo "  s390? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_s390x.tar.gz -> \${P}-chezmoi_\${PV}_linux_s390x.tar.gz  )  "
+                echo "  x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/chezmoi_\${PV}_linux_i386.tar.gz -> \${P}-chezmoi_\${PV}_linux_i386.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -137,15 +174,93 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64 && use glibc && ! use loong64 ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux-glibc_amd64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use amd64 && ! use glibc  && ! use loong64 ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux-musl_amd64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use amd64 && use loong64 && ! use glibc ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_loong64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_arm.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64 && use android; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_android_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64 && ! use android ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use ppc64 && ! use le ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_ppc64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use ppc64 && use le; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_ppc64le.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use riscv; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_riscv64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use s390; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_s390x.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-chezmoi_\${PV}_linux_i386.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use arm64 && use android; then'
+                echo '    newexe "${{ env.android_binary_archived_name_arm64 }}" "${{ env.android_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64 && ! use glibc  && ! use loong64 ; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_amd64 }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_arm }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64 && ! use android ; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_arm64 }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use ppc64 && ! use le ; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_ppc64 }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use riscv; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_riscv }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use s390; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_s390 }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.chezmoi_binary_archived_name_x86 }}" "${{ env.chezmoi_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64 && use glibc && ! use loong64 ; then'
+                echo '    newexe "${{ env.glibc_binary_archived_name_amd64 }}" "${{ env.glibc_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use ppc64 && use le; then'
+                echo '    newexe "${{ env.le_binary_archived_name_ppc64 }}" "${{ env.le_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64 && use loong64 && ! use glibc ; then'
+                echo '    newexe "${{ env.loong64_binary_archived_name_amd64 }}" "${{ env.loong64_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux-glibc_amd64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux-glibc_amd64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux-musl_amd64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux-musl_amd64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_loong64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_loong64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_arm.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_arm.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_android_arm64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_android_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_arm64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_ppc64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_ppc64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_ppc64le.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_ppc64le.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_riscv64.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_riscv64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_s390x.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_s390x.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/chezmoi_${version}_linux_i386.tar.gz" "${{ env.epn }}-${version}-chezmoi_${version}_linux_i386.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/app-misc-chatbox-appimage-update.yaml b/.github/workflows/app-misc-chatbox-appimage-update.yaml
--- a/.github/workflows/app-misc-chatbox-appimage-update.yaml
+++ b/.github/workflows/app-misc-chatbox-appimage-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github AppImage Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github AppImage Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: app-misc/chatbox-appimage update
 
@@ -24,10 +24,12 @@ env:
   homepage: "https://chatboxai.app"
   github_owner: Bin-Huang
   github_repo: chatbox
-  keywords:
+  keywords: ~amd64 ~arm64
   workflow_filename: app-misc-chatbox-appimage-update.yaml
   chatbox_desktop_file: 'xyz.chatboxapp.app.desktop'
-  chatbox_appimage_installed_name: ''
+  chatbox_appimage_installed_name: 'chatbox.AppImage'
+  chatbox_release_name_amd64: 'Chatbox.CE-\${PV}-x86_64.AppImage'
+  chatbox_release_name_arm64: 'Chatbox.CE-\${PV}-arm64.AppImage'
 
 jobs:
   check-and-create-ebuild:
@@ -47,7 +49,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -63,7 +66,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -116,9 +119,17 @@ jobs:
                 echo "inherit xdg-utils"
                 echo ''
                 echo 'SRC_URI="'
+                echo "  arm64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox.CE-\${PV}-arm64.AppImage -> \${P}-Chatbox.CE-\${PV}-arm64.AppImage )"
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox.CE-\${PV}-x86_64.AppImage -> \${P}-Chatbox.CE-\${PV}-x86_64.AppImage )"
                 echo '"'
                 echo ''
                 echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.chatbox_release_name_amd64 }}\" \"${{ env.chatbox_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.chatbox_release_name_arm64 }}\" \"${{ env.chatbox_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
                 echo '  chmod a+x "${{ env.chatbox_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
                 echo '  "./${{ env.chatbox_appimage_installed_name }}" --appimage-extract "${{ env.chatbox_desktop_file }}" || die "Failed to extract .desktop from appimage"'
                 echo '  "./${{ env.chatbox_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
@@ -151,6 +162,8 @@ jobs:
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox.CE-${version}-arm64.AppImage" "${{ env.epn }}-${version}-Chatbox.CE-${version}-arm64.AppImage" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Chatbox.CE-${version}-x86_64.AppImage" "${{ env.epn }}-${version}-Chatbox.CE-${version}-x86_64.AppImage" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/app-misc-dua-cli-bin-update.yaml b/.github/workflows/app-misc-dua-cli-bin-update.yaml
--- a/.github/workflows/app-misc-dua-cli-bin-update.yaml
+++ b/.github/workflows/app-misc-dua-cli-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: app-misc/dua-cli-bin update
 
@@ -24,9 +24,15 @@ env:
   homepage: "https://lib.rs/crates/dua-cli"
   github_owner: Byron
   github_repo: dua-cli
-  keywords:
+  keywords: ~amd64 ~arm ~arm64
   workflow_filename: app-misc-dua-cli-bin-update.yaml
-  dua_binary_installed_name: ''
+  dua_binary_installed_name: 'dua'
+  dua_binary_archived_name_amd64: 'dua-v2.29.2-x86_64-unknown-linux-musl/dua'
+  dua_release_name_amd64: 'dua-${tag}-x86_64-unknown-linux-musl.tar.gz'
+  dua_binary_archived_name_arm: 'dua-v2.29.2-arm-unknown-linux-gnueabihf/dua'
+  dua_release_name_arm: 'dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz'
+  dua_binary_archived_name_arm64: 'dua-v2.29.2-aarch64-unknown-linux-musl/dua'
+  dua_release_name_arm64: 'dua-${tag}-aarch64-unknown-linux-musl.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -46,7 +52,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -62,7 +69,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -108,6 +115,9 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/dua-${tag}-x86_64-unknown-linux-musl.tar.gz -> \${P}-dua-${tag}-x86_64-unknown-linux-musl.tar.gz  )  "
+                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz -> \${P}-dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/dua-${tag}-aarch64-unknown-linux-musl.tar.gz -> \${P}-dua-${tag}-aarch64-unknown-linux-musl.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -130,10 +140,29 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-dua-${tag}-x86_64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-dua-${tag}-aarch64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.dua_binary_archived_name_amd64 }}" "${{ env.dua_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.dua_binary_archived_name_arm }}" "${{ env.dua_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.dua_binary_archived_name_arm64 }}" "${{ env.dua_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '  if use doc; then'
                 echo '    if use amd64; then'
                 echo '      newdoc "dua-v2.29.2-x86_64-unknown-linux-musl/LICENSE" "dua-${TAG}-LICENSE" || die "Failed to install document dua-${TAG}-LICENSE"'
@@ -156,6 +185,9 @@ jobs:
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/dua-${tag}-x86_64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-dua-${tag}-x86_64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz" "${{ env.epn }}-${version}-dua-${tag}-arm-unknown-linux-gnueabihf.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/dua-${tag}-aarch64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-dua-${tag}-aarch64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/app-misc-ente-auth-appimage-update.yaml b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
--- a/.github/workflows/app-misc-ente-auth-appimage-update.yaml
+++ b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
@@ -69,144 +69,144 @@ jobs:
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
             cat <<-"EOF" > "$metadata_file"
-                      <?xml version="1.0" encoding="UTF-8"?>
-                      <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
-                      <pkgmetadata>
-                        <upstream>
-                          <remote-id type="github">ente-io/ente</remote-id>
-                        </upstream>
-                      </pkgmetadata>
-                      EOF
-                      fi
-                      declare -A releaseTypes=()
-                        tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
-                      # shellcheck disable=SC2086
-                      for tag in $tags; do
-                        version="${tag#auth-v}"
-                        if [ "${version}" = "${tag}" ]; then
-                            echo "$version == $tag so there is no auth-v removed skipping"
-                            continue
-                        fi
-                        # shellcheck disable=SC2034
-                        originalVersion="${version}"
-                        version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)\(\|\.\?\([0-9]\+\)\)\)$/\1_\5\3\7/')"
-                        if ! echo "${version}" | grep -E '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-                            echo "version: $version doesn't match regexp";
-                            continue;
-                        fi
-                        releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
-                        if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
-                            releaseTypes[${releaseType:=release}]="$version"
-                        else
-                            echo "Already have a newier ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
-                            continue
-                        fi
-                        # Check if ebuild exists, if it does, check if we need to RC bump due to size change
-                        highest_rev_ebuild=$(find "${ebuild_dir}" -maxdepth 1 \( -name "${{ env.epn }}-${version}.ebuild" -o -name "${{ env.epn }}-${version}-r*.ebuild" \) 2>/dev/null | sort -V | tail -n 1)
-                        ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
-                        needs_update=false
-                        revision_suffix=""
+          <?xml version="1.0" encoding="UTF-8"?>
+          <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
+          <pkgmetadata>
+            <upstream>
+              <remote-id type="github">ente-io/ente</remote-id>
+            </upstream>
+          </pkgmetadata>
+          EOF
+          fi
+          declare -A releaseTypes=()
+            tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
+          # shellcheck disable=SC2086
+          for tag in $tags; do
+            version="${tag#auth-v}"
+            if [ "${version}" = "${tag}" ]; then
+                echo "$version == $tag so there is no auth-v removed skipping"
+                continue
+            fi
+            # shellcheck disable=SC2034
+            originalVersion="${version}"
+            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)\(\|\.\?\([0-9]\+\)\)\)$/\1_\5\3\7/')"
+            if ! echo "${version}" | grep -E '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "version: $version doesn't match regexp";
+                continue;
+            fi
+            releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
+            if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
+                releaseTypes[${releaseType:=release}]="$version"
+            else
+                echo "Already have a newier ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
+                continue
+            fi
+            # Check if ebuild exists, if it does, check if we need to RC bump due to size change
+            highest_rev_ebuild=$(find "${ebuild_dir}" -maxdepth 1 \( -name "${{ env.epn }}-${version}.ebuild" -o -name "${{ env.epn }}-${version}-r*.ebuild" \) 2>/dev/null | sort -V | tail -n 1)
+            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
+            needs_update=false
+            revision_suffix=""
 
-                        if [ -z "$highest_rev_ebuild" ]; then
-                            needs_update=true
-                        else
-                            # Ebuild exists, check if upstream replaced the file by comparing sizes
-                            remote_size=$(curl -sL --head "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage" | grep -i 'content-length' | awk '{print $2}' | tr -d '\r')
+            if [ -z "$highest_rev_ebuild" ]; then
+                needs_update=true
+            else
+                # Ebuild exists, check if upstream replaced the file by comparing sizes
+                remote_size=$(curl -sL --head "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage" | grep -i 'content-length' | awk '{print $2}' | tr -d '\r')
 
-                            # Get local size from Manifest
-                            highest_rev_file=$(basename "$highest_rev_ebuild")
-                            # Strip .ebuild
-                            highest_rev_p="${highest_rev_file%.ebuild}"
-                            local_distfile="${highest_rev_p}-ente-${tag}-x86_64.AppImage"
-                            local_size=$(grep "DIST $local_distfile " "${ebuild_dir}/Manifest" | awk '{print $3}')
+                # Get local size from Manifest
+                highest_rev_file=$(basename "$highest_rev_ebuild")
+                # Strip .ebuild
+                highest_rev_p="${highest_rev_file%.ebuild}"
+                local_distfile="${highest_rev_p}-ente-${tag}-x86_64.AppImage"
+                local_size=$(grep "DIST $local_distfile " "${ebuild_dir}/Manifest" | awk '{print $3}')
 
-                            if [ -n "$remote_size" ] && [ -n "$local_size" ] && [ "$remote_size" != "$local_size" ]; then
-                                echo "Size mismatch for ${version}: remote $remote_size, local $local_size. RC bumping."
-                                needs_update=true
+                if [ -n "$remote_size" ] && [ -n "$local_size" ] && [ "$remote_size" != "$local_size" ]; then
+                    echo "Size mismatch for ${version}: remote $remote_size, local $local_size. RC bumping."
+                    needs_update=true
 
-                                # Calculate new revision
-                                if [[ "$highest_rev_file" =~ -r([0-9]+)\.ebuild$ ]]; then
-                                    current_rev="${BASH_REMATCH[1]}"
-                                    next_rev=$((current_rev + 1))
-                                    revision_suffix="-r${next_rev}"
-                                else
-                                    revision_suffix="-r1"
-                                fi
-                                ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}${revision_suffix}.ebuild"
-                                rm "$highest_rev_ebuild"
-                            fi
-                        fi
+                    # Calculate new revision
+                    if [[ "$highest_rev_file" =~ -r([0-9]+)\.ebuild$ ]]; then
+                        current_rev="${BASH_REMATCH[1]}"
+                        next_rev=$((current_rev + 1))
+                        revision_suffix="-r${next_rev}"
+                    else
+                        revision_suffix="-r1"
+                    fi
+                    ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}${revision_suffix}.ebuild"
+                    rm "$highest_rev_ebuild"
+                fi
+            fi
 
-                        if [ "$needs_update" = true ]; then
+            if [ "$needs_update" = true ]; then
 
-                          # shellcheck disable=SC2016
-                          {
-                            echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
-                            echo 'EAPI=8'
-                            echo "DESCRIPTION=\"${{ env.description }}\""
-                            echo "HOMEPAGE=\"${{ env.homepage }}\""
-                            echo 'LICENSE="MIT"'
-                            echo 'SLOT="0"'
-                            echo 'KEYWORDS="${{ env.keywords }}"'
-                            echo 'IUSE=""'
-                            echo 'DEPEND=""'
-                            echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
-                            echo 'S="${WORKDIR}"'
-                            echo 'RESTRICT="strip"'
-                            echo ''
-                            echo "inherit xdg-utils"
-                            echo ''
-                            echo 'SRC_URI="'
-                            echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage -> \${P}-ente-${tag}-x86_64.AppImage )"
-                            echo '"'
-                            echo ''
-                            echo 'src_unpack() {'
-                            echo '  if use amd64; then'
-                            echo "    cp \"\${DISTDIR}/\${P}-${{ env.ente_auth_release_name_amd64 }}\" \"${{ env.ente_auth_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
-                            echo '  fi'
-                            echo '  chmod a+x "${{ env.ente_auth_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
-                            echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "${{ env.ente_auth_desktop_file }}" || die "Failed to extract .desktop from appimage"'
-                            echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
-                            echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
-                            echo '}'
-                            echo ''
-                            echo 'src_prepare() {'
-                            echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.ente_auth_appimage_installed_name }}:' 'squashfs-root/${{ env.ente_auth_desktop_file }}'"
-                            echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
-                            echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
-                            echo '  eapply_user'
-                            echo '}'
-                            echo ''
-                            echo 'src_install() {'
-                            echo '  exeinto /opt/bin'
-                            echo '  doexe "${{ env.ente_auth_appimage_installed_name }}" || die "Failed to install AppImage"'
-                            echo '  insinto /usr/share/applications'
-                            echo '  doins "squashfs-root/${{ env.ente_auth_desktop_file }}" || die "Failed to install desktop file"'
-                            echo '  insinto /usr/share/icons'
-                            echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
-                            echo '  insinto /usr/share/pixmaps'
-                            echo '  doins squashfs-root/*.png || die "Failed to install icons"'
-                            echo '}'
-                            echo ""
-                            echo "pkg_postinst() {"
-                            echo "  xdg_desktop_database_update"
-                            echo "}"
-                            echo ""
-                          } > $ebuild_file
+              # shellcheck disable=SC2016
+              {
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
+                echo 'EAPI=8'
+                echo "DESCRIPTION=\"${{ env.description }}\""
+                echo "HOMEPAGE=\"${{ env.homepage }}\""
+                echo 'LICENSE="MIT"'
+                echo 'SLOT="0"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=""'
+                echo 'DEPEND=""'
+                echo 'RDEPEND="sys-libs/glibc sys-libs/zlib "'
+                echo 'S="${WORKDIR}"'
+                echo 'RESTRICT="strip"'
+                echo ''
+                echo "inherit xdg-utils"
+                echo ''
+                echo 'SRC_URI="'
+                echo "  amd64? ( https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage -> \${P}-ente-${tag}-x86_64.AppImage )"
+                echo '"'
+                echo ''
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    cp \"\${DISTDIR}/\${P}-${{ env.ente_auth_release_name_amd64 }}\" \"${{ env.ente_auth_appimage_installed_name }}\"  || die \"Can't copy downloaded file\""
+                echo '  fi'
+                echo '  chmod a+x "${{ env.ente_auth_appimage_installed_name }}"  || die "Can'\''t chmod archive file"'
+                echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "${{ env.ente_auth_desktop_file }}" || die "Failed to extract .desktop from appimage"'
+                echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "usr/share/icons" || die "Failed to extract hicolor icons from app image"'
+                echo '  "./${{ env.ente_auth_appimage_installed_name }}" --appimage-extract "*.png" || die "Failed to extract root icons from app image"'
+                echo '}'
+                echo ''
+                echo 'src_prepare() {'
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/${{ env.ente_auth_appimage_installed_name }}:' 'squashfs-root/${{ env.ente_auth_desktop_file }}'"
+                echo "  find squashfs-root -type f \( -name index.theme -or -name icon-theme.cache \) -exec rm {} \; "
+                echo "  find squashfs-root -type d -exec rmdir -p --ignore-fail-on-non-empty {} \; "
+                echo '  eapply_user'
+                echo '}'
+                echo ''
+                echo 'src_install() {'
+                echo '  exeinto /opt/bin'
+                echo '  doexe "${{ env.ente_auth_appimage_installed_name }}" || die "Failed to install AppImage"'
+                echo '  insinto /usr/share/applications'
+                echo '  doins "squashfs-root/${{ env.ente_auth_desktop_file }}" || die "Failed to install desktop file"'
+                echo '  insinto /usr/share/icons'
+                echo '  doins -r squashfs-root/usr/share/icons/hicolor || die "Failed to install icons"'
+                echo '  insinto /usr/share/pixmaps'
+                echo '  doins squashfs-root/*.png || die "Failed to install icons"'
+                echo '}'
+                echo ""
+                echo "pkg_postinst() {"
+                echo "  xdg_desktop_database_update"
+                echo "}"
+                echo ""
+              } > $ebuild_file
 
-                          # Manifest generation
+              # Manifest generation
 
-                          g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage" "${{ env.epn }}-${version}${revision_suffix}-ente-${tag}-x86_64.AppImage" "${ebuild_dir}/Manifest"
-                          echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
-                        fi
-                      done
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/ente-${tag}-x86_64.AppImage" "${{ env.epn }}-${version}${revision_suffix}-ente-${tag}-x86_64.AppImage" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
+            fi
+          done
 
-                  - name: Commit and push changes
-                    run: |
-                      ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-                      git add "./${ebuild_dir}"
-                      if git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}"; then
-                        git pull --rebase &&
-                        git push
-                      fi || true
-                    if: steps.process_releases.outputs.generated_tag
+      - name: Commit and push changes
+        run: |
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
+          git add "./${ebuild_dir}"
+          if git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}"; then
+            git pull --rebase &&
+            git push
+          fi || true
+        if: steps.process_releases.outputs.generated_tag
diff --git a/.github/workflows/app-misc-picocrypt-bin-update.yaml b/.github/workflows/app-misc-picocrypt-bin-update.yaml
--- a/.github/workflows/app-misc-picocrypt-bin-update.yaml
+++ b/.github/workflows/app-misc-picocrypt-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: app-misc/picocrypt-bin update
 
@@ -24,9 +24,10 @@ env:
   homepage: ""
   github_owner: Picocrypt
   github_repo: Picocrypt
-  keywords:
+  keywords: ~amd64
   workflow_filename: app-misc-picocrypt-bin-update.yaml
-  Picocrypt_binary_installed_name: ''
+  Picocrypt_binary_installed_name: 'Picocrypt'
+  Picocrypt_release_name_amd64: 'Picocrypt'
 
 jobs:
   check-and-create-ebuild:
@@ -46,7 +47,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -62,7 +64,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -104,6 +106,7 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/\${PV}/Picocrypt -> \${P}-Picocrypt  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -130,11 +133,15 @@ jobs:
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${DISTDIR}/${P}-${{ env.Picocrypt_release_name_amd64 }}" "${{ env.Picocrypt_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/Picocrypt" "${{ env.epn }}-${version}-Picocrypt" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/app-misc-rntocase-bin-update.yaml b/.github/workflows/app-misc-rntocase-bin-update.yaml
--- a/.github/workflows/app-misc-rntocase-bin-update.yaml
+++ b/.github/workflows/app-misc-rntocase-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: app-misc/rntocase-bin update
 
@@ -24,8 +24,79 @@ env:
   homepage: ""
   github_owner: arran4
   github_repo: rntocase
-  keywords:
+  keywords: ~amd64 ~arm64
   workflow_filename: app-misc-rntocase-bin-update.yaml
+  rnacronym_binary_installed_name: 'rnacronym'
+  rnacronym_binary_archived_name_amd64: 'rnacronym'
+  rnacronym_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rnacronym_binary_archived_name_arm64: 'rnacronym'
+  rnacronym_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rnreverse_binary_installed_name: 'rnreverse'
+  rnreverse_binary_archived_name_amd64: 'rnreverse'
+  rnreverse_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rnreverse_binary_archived_name_arm64: 'rnreverse'
+  rnreverse_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntocamel_binary_installed_name: 'rntocamel'
+  rntocamel_binary_archived_name_amd64: 'rntocamel'
+  rntocamel_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntocamel_binary_archived_name_arm64: 'rntocamel'
+  rntocamel_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntocase_binary_installed_name: ''
+  rntodarwin_binary_installed_name: 'rntodarwin'
+  rntodarwin_binary_archived_name_amd64: 'rntodarwin'
+  rntodarwin_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntodarwin_binary_archived_name_arm64: 'rntodarwin'
+  rntodarwin_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntodelimited_binary_installed_name: 'rntodelimited'
+  rntodelimited_binary_archived_name_amd64: 'rntodelimited'
+  rntodelimited_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntodelimited_binary_archived_name_arm64: 'rntodelimited'
+  rntodelimited_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntokebab_binary_installed_name: 'rntokebab'
+  rntokebab_binary_archived_name_amd64: 'rntokebab'
+  rntokebab_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntokebab_binary_archived_name_arm64: 'rntokebab'
+  rntokebab_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntolower_binary_installed_name: 'rntolower'
+  rntolower_binary_archived_name_amd64: 'rntolower'
+  rntolower_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntolower_binary_archived_name_arm64: 'rntolower'
+  rntolower_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntolowerleading_binary_installed_name: 'rntolowerleading'
+  rntolowerleading_binary_archived_name_amd64: 'rntolowerleading'
+  rntolowerleading_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntolowerleading_binary_archived_name_arm64: 'rntolowerleading'
+  rntolowerleading_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntopascal_binary_installed_name: 'rntopascal'
+  rntopascal_binary_archived_name_amd64: 'rntopascal'
+  rntopascal_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntopascal_binary_archived_name_arm64: 'rntopascal'
+  rntopascal_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntosnake_binary_installed_name: 'rntosnake'
+  rntosnake_binary_archived_name_amd64: 'rntosnake'
+  rntosnake_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntosnake_binary_archived_name_arm64: 'rntosnake'
+  rntosnake_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntotitle_binary_installed_name: 'rntotitle'
+  rntotitle_binary_archived_name_amd64: 'rntotitle'
+  rntotitle_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntotitle_binary_archived_name_arm64: 'rntotitle'
+  rntotitle_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntoupper_binary_installed_name: 'rntoupper'
+  rntoupper_binary_archived_name_amd64: 'rntoupper'
+  rntoupper_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntoupper_binary_archived_name_arm64: 'rntoupper'
+  rntoupper_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntoupperleading_binary_installed_name: 'rntoupperleading'
+  rntoupperleading_binary_archived_name_amd64: 'rntoupperleading'
+  rntoupperleading_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntoupperleading_binary_archived_name_arm64: 'rntoupperleading'
+  rntoupperleading_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntrim_binary_installed_name: 'rntrim'
+  rntrim_binary_archived_name_amd64: 'rntrim'
+  rntrim_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntrim_binary_archived_name_arm64: 'rntrim'
+  rntrim_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -45,7 +116,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -61,7 +133,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -107,6 +179,8 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/rntocase_\${PV}_linux_amd64.tar.gz -> \${P}-rntocase_\${PV}_linux_amd64.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/rntocase_\${PV}_linux_arm64.tar.gz -> \${P}-rntocase_\${PV}_linux_arm64.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -114,7 +188,7 @@ jobs:
                 echo -n 'IUSE="'
                 echo -n ''
                 echo -n ''
-                echo -n ''
+                echo -n ' doc'
                 echo -n ''
                 echo '"'
                 echo ''
@@ -129,15 +203,114 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-rntocase_\${PV}_linux_amd64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-rntocase_\${PV}_linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rnacronym_binary_archived_name_amd64 }}" "${{ env.rnacronym_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rnacronym_binary_archived_name_arm64 }}" "${{ env.rnacronym_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rnreverse_binary_archived_name_amd64 }}" "${{ env.rnreverse_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rnreverse_binary_archived_name_arm64 }}" "${{ env.rnreverse_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntocamel_binary_archived_name_amd64 }}" "${{ env.rntocamel_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntocamel_binary_archived_name_arm64 }}" "${{ env.rntocamel_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntodarwin_binary_archived_name_amd64 }}" "${{ env.rntodarwin_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntodarwin_binary_archived_name_arm64 }}" "${{ env.rntodarwin_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntodelimited_binary_archived_name_amd64 }}" "${{ env.rntodelimited_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntodelimited_binary_archived_name_arm64 }}" "${{ env.rntodelimited_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntokebab_binary_archived_name_amd64 }}" "${{ env.rntokebab_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntokebab_binary_archived_name_arm64 }}" "${{ env.rntokebab_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntolower_binary_archived_name_amd64 }}" "${{ env.rntolower_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntolower_binary_archived_name_arm64 }}" "${{ env.rntolower_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntolowerleading_binary_archived_name_amd64 }}" "${{ env.rntolowerleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntolowerleading_binary_archived_name_arm64 }}" "${{ env.rntolowerleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntopascal_binary_archived_name_amd64 }}" "${{ env.rntopascal_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntopascal_binary_archived_name_arm64 }}" "${{ env.rntopascal_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntosnake_binary_archived_name_amd64 }}" "${{ env.rntosnake_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntosnake_binary_archived_name_arm64 }}" "${{ env.rntosnake_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntotitle_binary_archived_name_amd64 }}" "${{ env.rntotitle_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntotitle_binary_archived_name_arm64 }}" "${{ env.rntotitle_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntoupper_binary_archived_name_amd64 }}" "${{ env.rntoupper_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntoupper_binary_archived_name_arm64 }}" "${{ env.rntoupper_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntoupperleading_binary_archived_name_amd64 }}" "${{ env.rntoupperleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntoupperleading_binary_archived_name_arm64 }}" "${{ env.rntoupperleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntrim_binary_archived_name_amd64 }}" "${{ env.rntrim_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntrim_binary_archived_name_arm64 }}" "${{ env.rntrim_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use doc; then'
+                echo '    if use amd64; then'
+                echo '      newdoc "LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      newdoc "LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '    fi'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rntocase_${version}_linux_amd64.tar.gz" "${{ env.epn }}-${version}-rntocase_${version}_linux_amd64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/rntocase_${version}_linux_arm64.tar.gz" "${{ env.epn }}-${version}-rntocase_${version}_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/dev-go-goreleaser-bin-update.yaml b/.github/workflows/dev-go-goreleaser-bin-update.yaml
--- a/.github/workflows/dev-go-goreleaser-bin-update.yaml
+++ b/.github/workflows/dev-go-goreleaser-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: dev-go/goreleaser-bin update
 
@@ -24,9 +24,19 @@ env:
   homepage: "https://goreleaser.com"
   github_owner: goreleaser
   github_repo: goreleaser
-  keywords:
+  keywords: ~amd64 ~arm ~arm64 ~ppc64 ~x86
   workflow_filename: dev-go-goreleaser-bin-update.yaml
-  goreleaser_binary_installed_name: ''
+  goreleaser_binary_installed_name: 'goreleaser'
+  goreleaser_binary_archived_name_amd64: 'goreleaser'
+  goreleaser_release_name_amd64: 'goreleaser_Linux_x86_64.tar.gz'
+  goreleaser_binary_archived_name_arm: 'goreleaser'
+  goreleaser_release_name_arm: 'goreleaser_Linux_armv7.tar.gz'
+  goreleaser_binary_archived_name_arm64: 'goreleaser'
+  goreleaser_release_name_arm64: 'goreleaser_Linux_arm64.tar.gz'
+  goreleaser_binary_archived_name_ppc64: 'goreleaser'
+  goreleaser_release_name_ppc64: 'goreleaser_Linux_ppc64.tar.gz'
+  goreleaser_binary_archived_name_x86: 'goreleaser'
+  goreleaser_release_name_x86: 'goreleaser_Linux_i386.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -46,7 +56,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -62,10 +73,15 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
+            <use>
+              <flag name="bash">Install bash completion</flag>
+              <flag name="fish">Install fish completion</flag>
+              <flag name="zsh">Install zsh completion</flag>
+            </use>
             <upstream>
               <remote-id type="github">goreleaser/goreleaser</remote-id>
             </upstream>
@@ -108,6 +124,11 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/goreleaser_Linux_x86_64.tar.gz -> \${P}-goreleaser_Linux_x86_64.tar.gz  )  "
+                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/goreleaser_Linux_armv7.tar.gz -> \${P}-goreleaser_Linux_armv7.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/goreleaser_Linux_arm64.tar.gz -> \${P}-goreleaser_Linux_arm64.tar.gz  )  "
+                echo "  ppc64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/goreleaser_Linux_ppc64.tar.gz -> \${P}-goreleaser_Linux_ppc64.tar.gz  )  "
+                echo "  x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/goreleaser_Linux_i386.tar.gz -> \${P}-goreleaser_Linux_i386.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -115,8 +136,8 @@ jobs:
                 echo -n 'IUSE="'
                 echo -n ''
                 echo -n ' man'
-                echo -n ''
-                echo -n ''
+                echo -n ' doc'
+                echo -n ' bash fish zsh'
                 echo '"'
                 echo ''
                 echo -n 'REQUIRED_USE="'
@@ -131,6 +152,21 @@ jobs:
                 echo 'S="${WORKDIR}"'
                 echo ''
                 echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_armv7.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use ppc64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_ppc64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_i386.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
                 echo '  if use man; then'
                 echo '    gzip -d "manpages/goreleaser.1.gz" || die "Failed to decompress manual page goreleaser.1"'
                 echo '  fi'
@@ -138,14 +174,50 @@ jobs:
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_amd64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_arm }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_arm64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use ppc64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_ppc64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_x86 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use bash; then'
+                echo '    insinto "/usr/share/bash-completion/completions"'
+                echo '    newins "completions/goreleaser.bash" "goreleaser.bash" || die "Failed to bash completion file"'
+                echo '  fi'
+                echo '  if use fish; then'
+                echo '    insinto "/usr/share/fish/vendor_completions.d"'
+                echo '    newins "completions/goreleaser.fish" "goreleaser.fish" || die "Failed to bash completion file"'
+                echo '  fi'
+                echo '  if use zsh; then'
+                echo '    insinto "/usr/share/zsh/site-functions"'
+                echo '    newins "completions/goreleaser.zsh" "goreleaser.zsh" || die "Failed to bash completion file"'
+                echo '  fi'
                 echo '  if use man; then'
                 echo '    newman "manpages/goreleaser.1" "goreleaser.1" || die "Failed to install manual page goreleaser.1"'
+                echo '  fi'
+                echo '  if use doc; then'
+                echo '    newdoc "LICENSE.md" "LICENSE.md" || die "Failed to install document LICENSE.md"'
+                echo '    newdoc "README.md" "README.md" || die "Failed to install document README.md"'
                 echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_armv7.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_armv7.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_ppc64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_ppc64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_i386.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_i386.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/media-sound-go-playerctl-bin-update.yaml b/.github/workflows/media-sound-go-playerctl-bin-update.yaml
--- a/.github/workflows/media-sound-go-playerctl-bin-update.yaml
+++ b/.github/workflows/media-sound-go-playerctl-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 07:05:49.55494487 +0000 UTC m=+0.007290831
 
 name: media-sound/go-playerctl-bin update
 
@@ -50,7 +50,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -121,7 +122,7 @@ jobs:
                 echo -n 'IUSE="'
                 echo -n ''
                 echo -n ''
-                echo -n ''
+                echo -n ' doc'
                 echo -n ''
                 echo '"'
                 echo ''
@@ -146,13 +147,18 @@ jobs:
                 echo '}'
                 echo ''
                 echo 'src_install() {'
-                echo '  exeinto /opt/bin'
+                echo '  exeinto /usr/bin'
                 echo '  if use amd64; then'
                 echo '    newexe "${{ env.go-playerctl_binary_archived_name_amd64 }}" "${{ env.go-playerctl_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '  if use arm64; then'
                 echo '    newexe "${{ env.go-playerctl_binary_archived_name_arm64 }}" "${{ env.go-playerctl_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
+                echo '  if use doc; then'
+                echo '    newdoc "COPYING" "COPYING" || die "Failed to install document COPYING"'
+                echo '    newdoc "README.md" "README.md" || die "Failed to install document README.md"'
+                echo '  fi'
+                echo '  dosym go-playerctl /usr/bin/go-playerctld'
                 echo '}'
               } > $ebuild_file
 
diff --git a/.github/workflows/net-im-beeper-appimage-update.yaml b/.github/workflows/net-im-beeper-appimage-update.yaml
--- a/.github/workflows/net-im-beeper-appimage-update.yaml
+++ b/.github/workflows/net-im-beeper-appimage-update.yaml
@@ -1,5 +1,3 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Web AppImage current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
-
 name: net-im/beeper-appimage update
 
 permissions:
@@ -18,8 +16,9 @@ env:
   epn: beeper-appimage
   description: "Unified chat client bridging multiple networks"
   homepage: "https://www.beeper.com"
-  keywords:
+  keywords: ~amd64
   workflow_filename: net-im-beeper-appimage-update.yaml
+  beeper_appimage_installed_name: 'beeper.AppImage'
 
 jobs:
   fetch-latest:
@@ -36,7 +35,19 @@ jobs:
       - name: Install required tools
         run: |
           sudo apt-get update
-          sudo apt-get install -y wget jq coreutils htmlq
+          sudo apt-get install -y wget jq coreutils
+          wget -qO- https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz | tar xz -C /usr/local/bin htmlq
+          if command -v go &> /dev/null
+          then
+              go install github.com/arran4/g2/cmd/g2@latest
+              sudo cp ~/go/bin/g2 /usr/local/bin/g2
+          else
+              url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+              echo "$url"
+              wget "${url}" -O /tmp/g2.deb
+              sudo dpkg -i /tmp/g2.deb
+              rm /tmp/g2.deb
+          fi
 
       - name: Determine latest AppImage
         id: find_appimage
@@ -70,7 +81,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata></pkgmetadata>
@@ -99,7 +110,14 @@ jobs:
               echo '  cp "${DISTDIR}/${P}.${appimage_extension}" "${P}.${appimage_extension}" || die "Failed to copy AppImage"'
               echo '  chmod a+x "${P}.${appimage_extension}" || die "Can'"'"'t chmod archive file"'
 
+
+
+
               echo '  exeinto /opt/bin'
+
+              echo '  newexe "${P}.${appimage_extension}" "${{ env.beeper_appimage_installed_name }}" || die "Failed to install AppImage"'
+
+
 
 
 
diff --git a/.github/workflows/net-im-slackdump-bin-update.yaml b/.github/workflows/net-im-slackdump-bin-update.yaml
--- a/.github/workflows/net-im-slackdump-bin-update.yaml
+++ b/.github/workflows/net-im-slackdump-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: net-im/slackdump-bin update
 
@@ -24,8 +24,15 @@ env:
   homepage: ""
   github_owner: rusq
   github_repo: slackdump
-  keywords:
+  keywords: ~amd64 ~arm64 ~x86
   workflow_filename: net-im-slackdump-bin-update.yaml
+  binary_installed_name: 'slackdump'
+  binary_archived_name_amd64: 'slackdump'
+  release_name_amd64: 'slackdump_Linux_x86_64.tar.gz'
+  binary_archived_name_arm64: 'slackdump'
+  release_name_arm64: 'slackdump_Linux_arm64.tar.gz'
+  binary_archived_name_x86: 'slackdump'
+  release_name_x86: 'slackdump_Linux_i386.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -45,7 +52,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -61,7 +69,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -108,6 +116,9 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/slackdump_Linux_x86_64.tar.gz -> \${P}-slackdump_Linux_x86_64.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/slackdump_Linux_arm64.tar.gz -> \${P}-slackdump_Linux_arm64.tar.gz  )  "
+                echo "  x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/slackdump_Linux_i386.tar.gz -> \${P}-slackdump_Linux_i386.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -130,15 +141,37 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_i386.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.binary_archived_name_amd64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.binary_archived_name_arm64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.binary_archived_name_x86 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_i386.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_i386.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/www-apps-hugo-bin-update.yaml b/.github/workflows/www-apps-hugo-bin-update.yaml
--- a/.github/workflows/www-apps-hugo-bin-update.yaml
+++ b/.github/workflows/www-apps-hugo-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: www-apps/hugo-bin update
 
@@ -24,9 +24,20 @@ env:
   homepage: "https://gohugo.io"
   github_owner: gohugoio
   github_repo: hugo
-  keywords:
+  keywords: ~amd64 ~arm ~arm64
   workflow_filename: www-apps-hugo-bin-update.yaml
-  extended_binary_installed_name: ''
+  binary_installed_name: 'hugo'
+  binary_archived_name_amd64: 'hugo'
+  release_name_amd64: 'hugo_\${PV}_linux-amd64.tar.gz'
+  binary_archived_name_arm: 'hugo'
+  release_name_arm: 'hugo_\${PV}_linux-arm.tar.gz'
+  binary_archived_name_arm64: 'hugo'
+  release_name_arm64: 'hugo_\${PV}_linux-arm64.tar.gz'
+  extended_binary_installed_name: 'hugo'
+  extended_binary_archived_name_amd64: 'hugo'
+  extended_release_name_amd64: 'hugo_extended_\${PV}_Linux-64bit.tar.gz'
+  extended_binary_archived_name_arm64: 'hugo'
+  extended_release_name_arm64: 'hugo_extended_\${PV}_linux-arm64.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -46,7 +57,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -62,13 +74,13 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
-              <use>
-                <flag name="extended">Install extended binary</flag>
-              </use>
+            <use>
+              <flag name="extended">Install extended binary</flag>
+            </use>
             <upstream>
               <remote-id type="github">gohugoio/hugo</remote-id>
             </upstream>
@@ -111,6 +123,11 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? ( !extended? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/hugo_\${PV}_linux-amd64.tar.gz -> \${P}-hugo_\${PV}_linux-amd64.tar.gz  )  )  "
+                echo "  amd64? ( extended? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/hugo_extended_\${PV}_Linux-64bit.tar.gz -> \${P}-hugo_extended_\${PV}_Linux-64bit.tar.gz  )  )  "
+                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/hugo_\${PV}_linux-arm.tar.gz -> \${P}-hugo_\${PV}_linux-arm.tar.gz  )  "
+                echo "  arm64? ( !extended? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/hugo_\${PV}_linux-arm64.tar.gz -> \${P}-hugo_\${PV}_linux-arm64.tar.gz  )  )  "
+                echo "  arm64? ( extended? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/hugo_extended_\${PV}_linux-arm64.tar.gz -> \${P}-hugo_extended_\${PV}_linux-arm64.tar.gz  )  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -133,15 +150,51 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64 && ! use extended ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-hugo_\${PV}_linux-amd64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use amd64 && use extended; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-hugo_extended_\${PV}_Linux-64bit.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-hugo_\${PV}_linux-arm.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64 && ! use extended ; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-hugo_\${PV}_linux-arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64 && use extended; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-hugo_extended_\${PV}_linux-arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64 && ! use extended ; then'
+                echo '    newexe "${{ env.binary_archived_name_amd64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.binary_archived_name_arm }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64 && ! use extended ; then'
+                echo '    newexe "${{ env.binary_archived_name_arm64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64 && use extended; then'
+                echo '    newexe "${{ env.extended_binary_archived_name_amd64 }}" "${{ env.extended_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64 && use extended; then'
+                echo '    newexe "${{ env.extended_binary_archived_name_arm64 }}" "${{ env.extended_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/hugo_${version}_linux-amd64.tar.gz" "${{ env.epn }}-${version}-hugo_${version}_linux-amd64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/hugo_extended_${version}_Linux-64bit.tar.gz" "${{ env.epn }}-${version}-hugo_extended_${version}_Linux-64bit.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/hugo_${version}_linux-arm.tar.gz" "${{ env.epn }}-${version}-hugo_${version}_linux-arm.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/hugo_${version}_linux-arm64.tar.gz" "${{ env.epn }}-${version}-hugo_${version}_linux-arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/hugo_extended_${version}_linux-arm64.tar.gz" "${{ env.epn }}-${version}-hugo_extended_${version}_linux-arm64.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
diff --git a/.github/workflows/www-apps-pagefind-bin-update.yaml b/.github/workflows/www-apps-pagefind-bin-update.yaml
--- a/.github/workflows/www-apps-pagefind-bin-update.yaml
+++ b/.github/workflows/www-apps-pagefind-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 22:47:00.15298246 +0000 UTC m=+0.013422929
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-03 10:16:15.640186701 +0000 UTC m=+0.016826779
 
 name: www-apps/pagefind-bin update
 
@@ -24,8 +24,18 @@ env:
   homepage: "https://pagefind.app"
   github_owner: CloudCannon
   github_repo: pagefind
-  keywords:
+  keywords: ~amd64 ~arm64
   workflow_filename: www-apps-pagefind-bin-update.yaml
+  binary_installed_name: 'pagefind'
+  binary_archived_name_amd64: 'pagefind'
+  release_name_amd64: 'pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz'
+  binary_archived_name_arm64: 'pagefind'
+  release_name_arm64: 'pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz'
+  extended_binary_installed_name: 'pagefind_extended'
+  extended_binary_archived_name_amd64: 'pagefind_extended'
+  extended_release_name_amd64: 'pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz'
+  extended_binary_archived_name_arm64: 'pagefind_extended'
+  extended_release_name_arm64: 'pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -45,7 +55,8 @@ jobs:
             sudo apt-get install -y wget jq coreutils
             if command -v go &> /dev/null
             then
-                go install github.com/arran4/g2@latest
+                go install github.com/arran4/g2/cmd/g2@latest
+                sudo cp ~/go/bin/g2 /usr/local/bin/g2
             else
                 url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
                 echo "$url"
@@ -61,7 +72,7 @@ jobs:
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
           if [ ! -f "$metadata_file" ]; then
-            cat <<EOF > "$metadata_file"
+            cat <<-"EOF" > "$metadata_file"
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
           <pkgmetadata>
@@ -107,6 +118,10 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz -> \${P}-pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz  )  "
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz -> \${P}-pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz -> \${P}-pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz -> \${P}-pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
@@ -129,15 +144,44 @@ jobs:
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
-                echo 'src_unpack() { :; }'
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.binary_archived_name_amd64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.binary_archived_name_arm64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.extended_binary_archived_name_amd64 }}" "${{ env.extended_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.extended_binary_archived_name_arm64 }}" "${{ env.extended_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
                 echo '}'
               } > $ebuild_file
 
               # Manifest generation
 
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-pagefind-${tag}-x86_64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-pagefind_extended-${tag}-x86_64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-pagefind-${tag}-aarch64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz" "${{ env.epn }}-${version}-pagefind_extended-${tag}-aarch64-unknown-linux-musl.tar.gz" "${ebuild_dir}/Manifest"
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
           done
