Interesting inconsistency

diff --git a/.github/workflows/app-misc-jan-appimage-update.yaml b/.github/workflows/app-misc-jan-appimage-update.yaml
--- a/.github/workflows/app-misc-jan-appimage-update.yaml
+++ b/.github/workflows/app-misc-jan-appimage-update.yaml
@@ -67,19 +67,19 @@ jobs:
                 echo 'src_unpack() {'
                 echo '  cp "${DISTDIR}/${A}" "${A}"  || die "Can'\''t copy archive file"'
                 echo '  chmod a+x "${A}"  || die "Can'\''t chmod archive file"'
-                echo "  ./${A} --appimage-extract ${env.desktop_file} || die \"Can't extract .desktop from appimage\""
+                echo "  ./${A} --appimage-extract ${{env.desktop_file}} || die \"Can't extract .desktop from appimage\""
                 echo "  ./${A} --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
-                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/jan:' squashfs-root/${env.desktop_file}"
+                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/jan:' squashfs-root/${{env.desktop_file}}"
                 echo '  eapply_user'
                 echo '}'
                 echo ''
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
                 echo '  doexe ${A}'
-                echo '  domenu squashfs-root/${env.desktop_file}'
+                echo '  domenu squashfs-root/${{env.desktop_file}}'
                 echo '  doicon squashfs-root/usr/share/icons/*'
                 echo '}'
                 echo ''
