Need to escape it

diff --git a/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml b/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
--- a/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
+++ b/.github/workflows/app-accessibility-whisperfiles-bin-update.yaml
@@ -109,7 +109,7 @@ jobs:
                     condition="${variant}"
                   fi
                   echo "    if use $condition; then"
-                  echo "      cp \"${DISTDIR}/${mvafn}\" '$mvfn' || die 'failed to move $mvfn'"
+                  echo "      cp \"\${DISTDIR}/${mvafn}\" '$mvfn' || die 'failed to move $mvfn'"
                   echo "      chmod +x '${mvfn}' || die 'failed to chmod $mvfn'"
                   echo "    fi"
                 done
