Pay attention

diff --git a/.github/workflows/app-misc-ente-auth-appimage-update.yaml b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
--- a/.github/workflows/app-misc-ente-auth-appimage-update.yaml
+++ b/.github/workflows/app-misc-ente-auth-appimage-update.yaml
@@ -66,9 +66,9 @@ jobs:
                 echo "inherit xdg-utils"
                 echo ""
                 echo "src_unpack() {"
-                echo "    chmod a+x \"\${DISTDIR}/\${A}\" || die 'Can't find archive file'"
-                echo "    \"\${DISTDIR}/\${A}\" --appimage-extract ente_auth.desktop || die 'Can't extract .desktop from appimage'"
-                echo "    \"\${DISTDIR}/\${A}\" --appimage-extract usr/share/icons || die 'Can't extract icons from app image'"
+                echo "    chmod a+x \"\${DISTDIR}/\${A}\" || die \"Can't find archive file\""
+                echo "    \"\${DISTDIR}/\${A}\" --appimage-extract ente_auth.desktop || die \"Can't extract .desktop from appimage\""
+                echo "    \"\${DISTDIR}/\${A}\" --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
                 echo "}"
                 echo ""
                 echo "src_prepare() {"
