Add app-misc/vhs-bin
Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>

diff --git a/.github/workflows/app-misc-vhs-bin-update.yaml b/.github/workflows/app-misc-vhs-bin-update.yaml
--- a/.github/workflows/app-misc-vhs-bin-update.yaml
+++ b/.github/workflows/app-misc-vhs-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder dev Github Binary Release current.config 2026-09-12 15:34:00.242316229 +0000 UTC m=+0.007526948
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder dev Github Binary Release current.config 2026-09-14 02:27:07.168507192 +0000 UTC m=+0.007392238
 
 name: app-misc/vhs-bin update
 
@@ -22,14 +22,14 @@ env:
   github_repo: vhs
   keywords: ~amd64 ~arm ~arm64 ~x86
   workflow_filename: app-misc-vhs-bin-update.yaml
-  vhs_binary_installed_name: 'vhs'
-  vhs_binary_archived_name_amd64: 'vhs_${version}_Linux_x86_64/vhs'
+  vhs_binary_installed_name: '/usr/bin/vhs'
+  vhs_binary_archived_name_amd64: 'vhs_${PV}_Linux_x86_64/vhs'
   vhs_release_name_amd64: 'vhs_${version}_Linux_x86_64.tar.gz'
-  vhs_binary_archived_name_arm: 'vhs_${version}_Linux_arm/vhs'
+  vhs_binary_archived_name_arm: 'vhs_${PV}_Linux_arm/vhs'
   vhs_release_name_arm: 'vhs_${version}_Linux_arm.tar.gz'
-  vhs_binary_archived_name_arm64: 'vhs_${version}_Linux_arm64/vhs'
+  vhs_binary_archived_name_arm64: 'vhs_${PV}_Linux_arm64/vhs'
   vhs_release_name_arm64: 'vhs_${version}_Linux_arm64.tar.gz'
-  vhs_binary_archived_name_x86: 'vhs_${version}_Linux_i386/vhs'
+  vhs_binary_archived_name_x86: 'vhs_${PV}_Linux_i386/vhs'
   vhs_release_name_x86: 'vhs_${version}_Linux_i386.tar.gz'
 
 concurrency:
@@ -110,6 +110,7 @@ jobs:
                 echo '"'
                 echo ''
                 echo -n 'RDEPEND="'
+                echo -n '( ) media-video/ffmpeg www-apps/ttyd www-client/chromium www-client/google-chrome www-client/google-chrome-beta www-client/google-chrome-unstable || '
                 echo '"'
                 echo ''
                 echo 'S="${WORKDIR}"'
@@ -129,16 +130,16 @@ jobs:
                 echo '  fi'
                 echo '  if use man; then'
                 echo '    if use amd64; then'
-                echo '      gzip -d "vhs_${VERSION}_Linux_x86_64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
+                echo '      gzip -d "vhs_${PV}_Linux_x86_64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
                 echo '    fi'
                 echo '    if use arm; then'
-                echo '      gzip -d "vhs_${VERSION}_Linux_arm/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
+                echo '      gzip -d "vhs_${PV}_Linux_arm/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
                 echo '    fi'
                 echo '    if use arm64; then'
-                echo '      gzip -d "vhs_${VERSION}_Linux_arm64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
+                echo '      gzip -d "vhs_${PV}_Linux_arm64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
                 echo '    fi'
                 echo '    if use x86; then'
-                echo '      gzip -d "vhs_${VERSION}_Linux_i386/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
+                echo '      gzip -d "vhs_${PV}_Linux_i386/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"'
                 echo '    fi'
                 echo '  fi'
                 echo '}'
@@ -159,34 +160,34 @@ jobs:
                 echo '  fi'
                 echo '  if use man; then'
                 echo '    if use amd64; then'
-                echo '      newman "vhs_${VERSION}_Linux_x86_64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
+                echo '      newman "vhs_${PV}_Linux_x86_64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
                 echo '    fi'
                 echo '    if use arm; then'
-                echo '      newman "vhs_${VERSION}_Linux_arm/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
+                echo '      newman "vhs_${PV}_Linux_arm/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
                 echo '    fi'
                 echo '    if use arm64; then'
-                echo '      newman "vhs_${VERSION}_Linux_arm64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
+                echo '      newman "vhs_${PV}_Linux_arm64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
                 echo '    fi'
                 echo '    if use x86; then'
-                echo '      newman "vhs_${VERSION}_Linux_i386/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
+                echo '      newman "vhs_${PV}_Linux_i386/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"'
                 echo '    fi'
                 echo '  fi'
                 echo '  if use doc; then'
                 echo '    if use amd64; then'
-                echo '      newdoc "vhs_${VERSION}_Linux_x86_64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
-                echo '      newdoc "vhs_${VERSION}_Linux_x86_64/README.md" "README.md" || die "Failed to install document README.md"'
+                echo '      newdoc "vhs_${PV}_Linux_x86_64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      newdoc "vhs_${PV}_Linux_x86_64/README.md" "README.md" || die "Failed to install document README.md"'
                 echo '    fi'
                 echo '    if use arm; then'
-                echo '      newdoc "vhs_${VERSION}_Linux_arm/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
-                echo '      newdoc "vhs_${VERSION}_Linux_arm/README.md" "README.md" || die "Failed to install document README.md"'
+                echo '      newdoc "vhs_${PV}_Linux_arm/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      newdoc "vhs_${PV}_Linux_arm/README.md" "README.md" || die "Failed to install document README.md"'
                 echo '    fi'
                 echo '    if use arm64; then'
-                echo '      newdoc "vhs_${VERSION}_Linux_arm64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
-                echo '      newdoc "vhs_${VERSION}_Linux_arm64/README.md" "README.md" || die "Failed to install document README.md"'
+                echo '      newdoc "vhs_${PV}_Linux_arm64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      newdoc "vhs_${PV}_Linux_arm64/README.md" "README.md" || die "Failed to install document README.md"'
                 echo '    fi'
                 echo '    if use x86; then'
-                echo '      newdoc "vhs_${VERSION}_Linux_i386/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
-                echo '      newdoc "vhs_${VERSION}_Linux_i386/README.md" "README.md" || die "Failed to install document README.md"'
+                echo '      newdoc "vhs_${PV}_Linux_i386/LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      newdoc "vhs_${PV}_Linux_i386/README.md" "README.md" || die "Failed to install document README.md"'
                 echo '    fi'
                 echo '  fi'
                 echo '}'
