Proper program support this time

diff --git a/.github/workflows/app-misc-rntocase-bin-update.yaml b/.github/workflows/app-misc-rntocase-bin-update.yaml
--- a/.github/workflows/app-misc-rntocase-bin-update.yaml
+++ b/.github/workflows/app-misc-rntocase-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.17 Github Binary Release ./current.config 2024-12-09 16:31:50.725743666 +1100 AEDT m=+0.001735559
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.17 Github Binary Release ./current.config 2024-12-09 16:57:17.889235419 +1100 AEDT m=+0.002080477
 
 name: app-misc/rntocase-bin update
 
@@ -26,11 +26,57 @@ env:
   github_repo: rntocase
   keywords: ~amd64 ~arm64
   workflow_filename: app-misc-rntocase-bin-update.yaml
-  rntocase_binary_installed_name: 'rntrim'
-  rntocase_binary_archived_name_amd64: 'rnreverse'
-  rntocase_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
-  rntocase_binary_archived_name_arm64: 'rnreverse'
-  rntocase_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rnreverse_binary_installed_name: 'rnreverse'
+  rnreverse_binary_archived_name_amd64: 'rnreverse'
+  rnreverse_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rnreverse_binary_archived_name_arm64: 'rnreverse'
+  rnreverse_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntocamel_binary_installed_name: 'rntocamel'
+  rntocamel_binary_archived_name_amd64: 'rntocamel'
+  rntocamel_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntocamel_binary_archived_name_arm64: 'rntocamel'
+  rntocamel_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntocase_binary_installed_name: ''
+  rntodarwin_binary_installed_name: 'rntodarwin'
+  rntodarwin_binary_archived_name_amd64: 'rntodarwin'
+  rntodarwin_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntodarwin_binary_archived_name_arm64: 'rntodarwin'
+  rntodarwin_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntodelimited_binary_installed_name: 'rntodelimited'
+  rntodelimited_binary_archived_name_amd64: 'rntodelimited'
+  rntodelimited_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntodelimited_binary_archived_name_arm64: 'rntodelimited'
+  rntodelimited_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntokebab_binary_installed_name: 'rntokebab'
+  rntokebab_binary_archived_name_amd64: 'rntokebab'
+  rntokebab_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntokebab_binary_archived_name_arm64: 'rntokebab'
+  rntokebab_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntolowerleading_binary_installed_name: 'rntolowerleading'
+  rntolowerleading_binary_archived_name_amd64: 'rntolowerleading'
+  rntolowerleading_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntolowerleading_binary_archived_name_arm64: 'rntolowerleading'
+  rntolowerleading_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntosnake_binary_installed_name: 'rntosnake'
+  rntosnake_binary_archived_name_amd64: 'rntosnake'
+  rntosnake_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntosnake_binary_archived_name_arm64: 'rntosnake'
+  rntosnake_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntotitle_binary_installed_name: 'rntotitle'
+  rntotitle_binary_archived_name_amd64: 'rntotitle'
+  rntotitle_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntotitle_binary_archived_name_arm64: 'rntotitle'
+  rntotitle_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntoupperleading_binary_installed_name: 'rntoupperleading'
+  rntoupperleading_binary_archived_name_amd64: 'rntoupperleading'
+  rntoupperleading_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntoupperleading_binary_archived_name_arm64: 'rntoupperleading'
+  rntoupperleading_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
+  rntrim_binary_installed_name: 'rntrim'
+  rntrim_binary_archived_name_amd64: 'rntrim'
+  rntrim_release_name_amd64: 'rntocase_\${PV}_linux_amd64.tar.gz'
+  rntrim_binary_archived_name_arm64: 'rntrim'
+  rntrim_release_name_arm64: 'rntocase_\${PV}_linux_arm64.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -118,10 +164,64 @@ jobs:
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
                 echo '  if use amd64; then'
-                echo '    newexe "${{ env.rntocase_binary_archived_name_amd64 }}" "${{ env.rntocase_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '    newexe "${{ env.rnreverse_binary_archived_name_amd64 }}" "${{ env.rnreverse_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '  if use arm64; then'
-                echo '    newexe "${{ env.rntocase_binary_archived_name_arm64 }}" "${{ env.rntocase_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '    newexe "${{ env.rnreverse_binary_archived_name_arm64 }}" "${{ env.rnreverse_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntocamel_binary_archived_name_amd64 }}" "${{ env.rntocamel_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntocamel_binary_archived_name_arm64 }}" "${{ env.rntocamel_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntodarwin_binary_archived_name_amd64 }}" "${{ env.rntodarwin_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntodarwin_binary_archived_name_arm64 }}" "${{ env.rntodarwin_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntodelimited_binary_archived_name_amd64 }}" "${{ env.rntodelimited_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntodelimited_binary_archived_name_arm64 }}" "${{ env.rntodelimited_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntokebab_binary_archived_name_amd64 }}" "${{ env.rntokebab_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntokebab_binary_archived_name_arm64 }}" "${{ env.rntokebab_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntolowerleading_binary_archived_name_amd64 }}" "${{ env.rntolowerleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntolowerleading_binary_archived_name_arm64 }}" "${{ env.rntolowerleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntosnake_binary_archived_name_amd64 }}" "${{ env.rntosnake_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntosnake_binary_archived_name_arm64 }}" "${{ env.rntosnake_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntotitle_binary_archived_name_amd64 }}" "${{ env.rntotitle_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntotitle_binary_archived_name_arm64 }}" "${{ env.rntotitle_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntoupperleading_binary_archived_name_amd64 }}" "${{ env.rntoupperleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntoupperleading_binary_archived_name_arm64 }}" "${{ env.rntoupperleading_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.rntrim_binary_archived_name_amd64 }}" "${{ env.rntrim_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.rntrim_binary_archived_name_arm64 }}" "${{ env.rntrim_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '  if use doc; then'
                 echo '    if use amd64; then'
