Root fs file error fix

diff --git a/.github/workflows/dev-ml-ollama-bin-update.yaml b/.github/workflows/dev-ml-ollama-bin-update.yaml
--- a/.github/workflows/dev-ml-ollama-bin-update.yaml
+++ b/.github/workflows/dev-ml-ollama-bin-update.yaml
@@ -93,12 +93,12 @@ jobs:
                 echo ""
                 echo "src_install() {"
                 echo '  if use amd64; then'
-                echo '    cp "${DISTDIR}/${P}.amd64" "${D}/ollama"'
+                echo '    cp "${DISTDIR}/${P}.amd64" "${WORKDIR}/ollama"'
                 echo '  elif use arm64; then'
-                echo '    cp "${DISTDIR}/${P}.arm64" "${D}/ollama"'
+                echo '    cp "${DISTDIR}/${P}.arm64" "${WORKDIR}/ollama"'
                 echo '  fi'
                 echo '  exeinto /opt/Ollama'
-                echo '  doexe "${D}/ollama" || die "Failed to install binary"'
+                echo '  doexe "${WORKDIR}/ollama" || die "Failed to install binary"'
                 echo '  fperms +x /opt/Ollama/ollama'
                 echo '  dosym /opt/Ollama/ollama /opt/bin/ollama'
                 echo "}"
