No libinto

diff --git a/.github/workflows/dev-ml-ollama-bin-update.yaml b/.github/workflows/dev-ml-ollama-bin-update.yaml
--- a/.github/workflows/dev-ml-ollama-bin-update.yaml
+++ b/.github/workflows/dev-ml-ollama-bin-update.yaml
@@ -102,8 +102,8 @@ jobs:
                 echo "src_install() {"
                 echo '  exeinto /opt/Ollama/bin'
                 echo '  doexe "${WORKDIR}/bin/ollama" || die "Failed to install binary"'
-                echo '  libinto /opt/Ollama/lib/ollama/'
-                echo '  newlib -r "${WORKDIR}/lib/ollama/" || die "Failed to install libraries"'
+                echo '  insinto /opt/Ollama/lib/'
+                echo '  doins -r "${WORKDIR}/lib/ollama/" || die "Failed to install libraries"'
                 echo '  dosym /opt/Ollama/bin/ollama /opt/bin/ollama'
                 echo "}"
                 echo ""
