Try 2

diff --git a/.github/workflows/dev-ml-ollama-bin-update.yaml b/.github/workflows/dev-ml-ollama-bin-update.yaml
--- a/.github/workflows/dev-ml-ollama-bin-update.yaml
+++ b/.github/workflows/dev-ml-ollama-bin-update.yaml
@@ -92,14 +92,12 @@ jobs:
                 echo "}"
                 echo ""
                 echo "src_install() {"
-                echo '  if use amd64; then'
-                echo '    mv "${DISTDIR}/${P}.amd64" "${WORKDIR}/ollama"'
-                echo '  elif use arm64; then'
-                echo '    mv "${DISTDIR}/${P}.arm64" "${WORKDIR}/ollama"'
-                echo '  fi'
                 echo '  exeinto /opt/Ollama'
-                echo '  doexe "${WORKDIR}/ollama" || die "Failed to install binary"'
-                echo '  fperms +x /opt/Ollama/ollama'
+                echo '  if use amd64; then'
+                echo '    newexe "${DISTDIR}/${P}.amd64" "ollama"' || die "Failed to install binary"'
+                echo '  elif use arm64; then'
+                echo '    newexe "${DISTDIR}/${P}.arm64" "ollama"' || die "Failed to install binary"'
+                echo '  fi'
                 echo '  dosym /opt/Ollama/ollama /opt/bin/ollama'
                 echo "}"
                 echo ""
