Update workflows with latest generator
Updated workflows using overlay_workflow_builder_generator v0.1.39 and fixed the generated profiles/repo_name and profiles/eapi bug.

Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>

diff --git a/.github/workflows/dev-go-txtar-bin-update.yaml b/.github/workflows/dev-go-txtar-bin-update.yaml
--- a/.github/workflows/dev-go-txtar-bin-update.yaml
+++ b/.github/workflows/dev-go-txtar-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.37 Github Binary Release current.config 2026-08-08 02:25:30.315825917 +0000 UTC m=+0.007226808
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.39 Github Binary Release current.config 2026-08-13 09:21:15.269769781 +0000 UTC m=+0.006636584
 
 name: dev-go/txtar-bin update
 
@@ -12,10 +12,6 @@ on:
   push:
     paths:
       - '.github/workflows/dev-go-txtar-bin-update.yaml'
-
-concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: false
 
 env:
   ecn: dev-go
@@ -31,6 +27,10 @@ env:
   txtar_release_name_amd64: 'txtar_${tag}_linux_amd64.tar.gz'
   txtar_binary_archived_name_arm64: 'txtar'
   txtar_release_name_arm64: 'txtar_${tag}_linux_arm64.tar.gz'
+
+concurrency:
+  group: ci-${{ github.ref }}
+  cancel-in-progress: false
 
 jobs:
   check-and-create-ebuild:
@@ -127,8 +127,8 @@ jobs:
                 echo '  fi'
                 echo '  if use doc; then'
                 echo '    if use amd64; then'
-                echo '      newdoc "LICENSE" "LICENSE" || die "Failed to install document LICENSE"'
-                echo '      newdoc "README.md" "README.md" || die "Failed to install document README.md"'
+                echo '      dodoc "LICENSE" || die "Failed to install document LICENSE"'
+                echo '      dodoc "README.md" || die "Failed to install document README.md"'
                 echo '    fi'
                 echo '  fi'
                 echo '}'
@@ -153,28 +153,31 @@ jobs:
               fi
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
           done
+
+      - name: Deduplicate ebuilds
+        run: |
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           g2 ebuild deduplicate "${ebuild_dir}"
 
       - name: Generate Overlay
         run: |
-          mkdir -p profiles
-          [ ! -f profiles/repo_name ] && echo "overlay_name" > profiles/repo_name || true
-          [ ! -f profiles/eapi ] && echo "8" > profiles/eapi || true
-          g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p metadata/md5-cache
-          cp -r metadata/md5-dict/* metadata/md5-cache/ || true
+          mkdir -p profiles metadata
+          [ ! -f profiles/repo_name ] && echo "overlay_name" > profiles/repo_name
+          [ ! -f profiles/eapi ] && echo "8" > profiles/eapi
+          [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true
+          if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi
 
       - name: Lint output
+        if: steps.process_releases.outputs.generated_tag
         uses: arran4/g2-action@v1.2
         with:
           mode: 'run'
-          action: 'lint . ${{ env.ecn }}/${{ env.epn }}'
-        if: steps.process_releases.outputs.generated_tag
+          action: 'lint -disable-rule PG0802 . ${{ env.ecn }}/${{ env.epn }}'
 
       - name: Commit and push changes
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p profiles; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi; g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
+          mkdir -p profiles metadata; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi; [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true; if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi; g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
           git add "./${ebuild_dir}"
           if git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}"; then
             git pull --rebase &&
diff --git a/.github/workflows/dev-util-antigravity-cli-bin-update.yaml b/.github/workflows/dev-util-antigravity-cli-bin-update.yaml
--- a/.github/workflows/dev-util-antigravity-cli-bin-update.yaml
+++ b/.github/workflows/dev-util-antigravity-cli-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.31 Github Binary Release current.config 2026-07-30 09:04:19.177157275 +0000 UTC m=+0.006149846
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.39 Github Binary Release current.config 2026-08-13 09:21:15.269769781 +0000 UTC m=+0.006636584
 
 name: dev-util/antigravity-cli-bin update
 
@@ -13,10 +13,6 @@ on:
     paths:
       - '.github/workflows/dev-util-antigravity-cli-bin-update.yaml'
 
-concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: false
-
 env:
   ecn: dev-util
   epn: antigravity-cli-bin
@@ -26,18 +22,22 @@ env:
   github_repo: antigravity-cli
   keywords: ~amd64 ~arm64
   workflow_filename: dev-util-antigravity-cli-bin-update.yaml
-  antigravity_binary_installed_name: 'agy'
-  antigravity_binary_archived_name_amd64: 'antigravity'
-  antigravity_release_name_amd64: 'agy_cli_linux_x64.tar.gz'
-  antigravity_binary_archived_name_arm64: 'antigravity'
-  antigravity_release_name_arm64: 'agy_cli_linux_arm64.tar.gz'
+  agy_binary_installed_name: 'agy'
+  agy_binary_archived_name_amd64: 'antigravity'
+  agy_release_name_amd64: 'agy_cli_linux_x64.tar.gz'
+  agy_binary_archived_name_arm64: 'antigravity'
+  agy_release_name_arm64: 'agy_cli_linux_arm64.tar.gz'
+
+concurrency:
+  group: ci-${{ github.ref }}
+  cancel-in-progress: false
 
 jobs:
   check-and-create-ebuild:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v7
 
       - name: Set up Git
         run: |
@@ -58,13 +58,14 @@ jobs:
           tags=$(GH_TOKEN="${{secrets.GITHUB_TOKEN}}" gh api "repos/${{ env.github_owner }}/${{ env.github_repo }}/releases" --jq '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
           # shellcheck disable=SC2086
           for tag in $tags; do
-            version="${tag#v}"
+            version="${tag}"
             # shellcheck disable=SC2034
             originalVersion="${version}"
-            #if ! echo "${version}" | grep -E '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-                #echo "tag / $version doesn't match regexp";
-                #continue;
-            #fi
+            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)[0-9]*\)$/\1_\5\3/')"
+            if ! echo "${version}" | grep -E '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue;
+            fi
             releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
             if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
                 if [[ -v releaseTypes[release] ]]; then
@@ -85,8 +86,8 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
-                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/\${PV}/agy_cli_linux_x64.tar.gz -> \${P}-agy_cli_linux_x64.tar.gz  )  "
-                echo "	arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/\${PV}/agy_cli_linux_arm64.tar.gz -> \${P}-agy_cli_linux_arm64.tar.gz  )  "
+                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${PV} -> \${P}-agy_cli_linux_x64.tar.gz  )  "
+                echo "	arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${PV} -> \${P}-agy_cli_linux_arm64.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="Apache-2.0"'
                 echo 'SLOT="0"'
@@ -115,10 +116,10 @@ jobs:
                 echo 'src_install() {'
                 echo '  exeinto /opt/bin'
                 echo '  if use amd64; then'
-                echo '    newexe "${{ env.antigravity_binary_archived_name_amd64 }}" "${{ env.antigravity_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '    newexe "${{ env.agy_binary_archived_name_amd64 }}" "${{ env.agy_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '  if use arm64; then'
-                echo '    newexe "${{ env.antigravity_binary_archived_name_arm64 }}" "${{ env.antigravity_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '    newexe "${{ env.agy_binary_archived_name_arm64 }}" "${{ env.agy_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '}'
               } > "$tmp_ebuild_file"
@@ -132,10 +133,9 @@ jobs:
                   rm -f "$tmp_ebuild_file"
                   continue
               fi
-              # Manifest generation
               failed=0
-              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/agy_cli_linux_x64.tar.gz" "${{ env.epn }}-${version}-agy_cli_linux_x64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
-              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/agy_cli_linux_arm64.tar.gz" "${{ env.epn }}-${version}-agy_cli_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
+              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${P}" "${{ env.epn }}-${version}-agy_cli_linux_x64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
+              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${P}" "${{ env.epn }}-${version}-agy_cli_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
               if [ "$failed" -eq 1 ]; then
                   echo "Failed to generate manifest for $tag. Skipping..."
                   rm -f "$ebuild_file"
@@ -144,26 +144,30 @@ jobs:
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
           done
 
+      - name: Deduplicate ebuilds
+        run: |
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
+          g2 ebuild deduplicate "${ebuild_dir}"
+
       - name: Generate Overlay
         run: |
-          mkdir -p profiles
-          [ ! -f profiles/repo_name ] && echo "overlay_name" > profiles/repo_name || true
-          [ ! -f profiles/eapi ] && echo "8" > profiles/eapi || true
-          g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p metadata/md5-cache
-          cp -r metadata/md5-dict/* metadata/md5-cache/ || true
+          mkdir -p profiles metadata
+          [ ! -f profiles/repo_name ] && echo "overlay_name" > profiles/repo_name
+          [ ! -f profiles/eapi ] && echo "8" > profiles/eapi
+          [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true
+          if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi
 
       - name: Lint output
+        if: steps.process_releases.outputs.generated_tag
         uses: arran4/g2-action@v1.2
         with:
           mode: 'run'
-          action: 'lint ${{ env.ecn }}/${{ env.epn }}'
-        if: steps.process_releases.outputs.generated_tag
+          action: 'lint -disable-rule PG0802 . ${{ env.ecn }}/${{ env.epn }}'
 
       - name: Commit and push changes
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p profiles; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi
+          mkdir -p profiles metadata; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi; [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true; if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi; g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
           git add "./${ebuild_dir}"
           if git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}"; then
             git pull --rebase &&
diff --git a/.github/workflows/media-sound-go-playerctl-bin-update.yaml b/.github/workflows/media-sound-go-playerctl-bin-update.yaml
--- a/.github/workflows/media-sound-go-playerctl-bin-update.yaml
+++ b/.github/workflows/media-sound-go-playerctl-bin-update.yaml
@@ -1,4 +1,4 @@
-# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.23 Github Binary Release current.config 2026-03-14 07:05:49.55494487 +0000 UTC m=+0.007290831
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder 0.1.39 Github Binary Release current.config 2026-08-13 09:21:15.269769781 +0000 UTC m=+0.006636584
 
 name: media-sound/go-playerctl-bin update
 
@@ -13,10 +13,6 @@ on:
     paths:
       - '.github/workflows/media-sound-go-playerctl-bin-update.yaml'
 
-concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: false
-
 env:
   ecn: media-sound
   epn: go-playerctl-bin
@@ -28,36 +24,36 @@ env:
   workflow_filename: media-sound-go-playerctl-bin-update.yaml
   go-playerctl_binary_installed_name: 'go-playerctl'
   go-playerctl_binary_archived_name_amd64: 'goplayerctl'
-  go-playerctl_release_name_amd64: 'go-playerctl_\${PV}_linux_amd64.tar.gz'
+  go-playerctl_release_name_amd64: 'go-playerctl_${version}_linux_amd64.tar.gz'
   go-playerctl_binary_archived_name_arm64: 'goplayerctl'
-  go-playerctl_release_name_arm64: 'go-playerctl_\${PV}_linux_arm64.tar.gz'
+  go-playerctl_release_name_arm64: 'go-playerctl_${version}_linux_arm64.tar.gz'
+
+concurrency:
+  group: ci-${{ github.ref }}
+  cancel-in-progress: false
 
 jobs:
   check-and-create-ebuild:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Install g2
-        uses: arran4/g2-action@v1.2
+        uses: actions/checkout@v7
 
       - name: Set up Git
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
-      - name: Install required tools
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y wget jq coreutils
+      - name: Install g2
+        uses: arran4/g2-action@v1.2
+
       - name: Process each release
         id: process_releases
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p "$ebuild_dir"
           metadata_file="${ebuild_dir}/metadata.xml"
-          g2 metadata -m "gentoo@arran4.com:Arran Ubels:person" -u "github:${{ env.github_owner }}/${{ env.github_repo }}" "$metadata_file"
+          g2 metadata -m "gentoo@arran4.com:Arran Ubels:person" -u "github:arran4/go-playerctl" --use-add "amd64:Enable amd64" --use-add "arm64:Enable arm64" "$metadata_file"
           declare -A releaseTypes=()
           tags=$(GH_TOKEN="${{secrets.GITHUB_TOKEN}}" gh api "repos/${{ env.github_owner }}/${{ env.github_repo }}/releases" --jq '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
           # shellcheck disable=SC2086
@@ -85,6 +81,7 @@ jobs:
                 continue
             fi
             tmp_ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild.tmp"
+
               # shellcheck disable=SC2016
               {
                 echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
@@ -92,26 +89,22 @@ jobs:
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
                 echo 'SRC_URI="'
-                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/go-playerctl_\${PV}_linux_amd64.tar.gz -> \${P}-go-playerctl_\${PV}_linux_amd64.tar.gz  )  "
-                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/go-playerctl_\${PV}_linux_arm64.tar.gz -> \${P}-go-playerctl_\${PV}_linux_arm64.tar.gz  )  "
+                echo "	amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${PV} -> \${P}-go-playerctl_\${PV}_linux_amd64.tar.gz  )  "
+                echo "	arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/\${PV} -> \${P}-go-playerctl_\${PV}_linux_arm64.tar.gz  )  "
                 echo '"'
                 echo 'LICENSE="LGPL-3"'
                 echo 'SLOT="0"'
                 echo 'KEYWORDS="${{ env.keywords }}"'
                 echo -n 'IUSE="'
-                echo -n ''
-                echo -n ''
                 echo -n ' doc'
-                echo -n ''
+                echo -n ' amd64 arm64'
                 echo '"'
                 echo ''
                 echo -n 'REQUIRED_USE="'
-                echo -n ''
                 echo '"'
                 echo ''
                 echo -n 'RDEPEND="'
                 echo -n '!media-sound/go-playerctl '
-                echo -n ''
                 echo '"'
                 echo ''
                 echo 'S="${WORKDIR}"'
@@ -126,7 +119,7 @@ jobs:
                 echo '}'
                 echo ''
                 echo 'src_install() {'
-                echo '  exeinto /usr/bin'
+                echo '  exeinto /opt/bin'
                 echo '  if use amd64; then'
                 echo '    newexe "${{ env.go-playerctl_binary_archived_name_amd64 }}" "${{ env.go-playerctl_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
@@ -134,10 +127,9 @@ jobs:
                 echo '    newexe "${{ env.go-playerctl_binary_archived_name_arm64 }}" "${{ env.go-playerctl_binary_installed_name }}" || die "Failed to install Binary"'
                 echo '  fi'
                 echo '  if use doc; then'
-                echo '    newdoc "COPYING" "COPYING" || die "Failed to install document COPYING"'
-                echo '    newdoc "README.md" "README.md" || die "Failed to install document README.md"'
+                echo '    dodoc "COPYING" || die "Failed to install document COPYING"'
+                echo '    dodoc "README.md" || die "Failed to install document README.md"'
                 echo '  fi'
-                echo '  dosym go-playerctl /usr/bin/go-playerctld'
                 echo '}'
               } > "$tmp_ebuild_file"
               if next_version=$(g2 ebuild next-revision --inspect "$tmp_ebuild_file" "${ebuild_dir}" "${version}"); then
@@ -150,12 +142,9 @@ jobs:
                   rm -f "$tmp_ebuild_file"
                   continue
               fi
-
-              # Manifest generation
-
               failed=0
-              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/go-playerctl_${version}_linux_amd64.tar.gz" "${{ env.epn }}-${version}-go-playerctl_${version}_linux_amd64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
-              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/go-playerctl_${version}_linux_arm64.tar.gz" "${{ env.epn }}-${version}-go-playerctl_${version}_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
+              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/${version}" "${{ env.epn }}-${version}-go-playerctl_${version}_linux_amd64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
+              if ! g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/${version}" "${{ env.epn }}-${version}-go-playerctl_${version}_linux_arm64.tar.gz" "${ebuild_dir}/Manifest"; then failed=1; fi
               if [ "$failed" -eq 1 ]; then
                   echo "Failed to generate manifest for $tag. Skipping..."
                   rm -f "$ebuild_file"
@@ -164,10 +153,30 @@ jobs:
               echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
           done
 
+      - name: Deduplicate ebuilds
+        run: |
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
+          g2 ebuild deduplicate "${ebuild_dir}"
+
+      - name: Generate Overlay
+        run: |
+          mkdir -p profiles metadata
+          [ ! -f profiles/repo_name ] && echo "overlay_name" > profiles/repo_name
+          [ ! -f profiles/eapi ] && echo "8" > profiles/eapi
+          [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true
+          if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi
+
+      - name: Lint output
+        if: steps.process_releases.outputs.generated_tag
+        uses: arran4/g2-action@v1.2
+        with:
+          mode: 'run'
+          action: 'lint -disable-rule PG0802 . ${{ env.ecn }}/${{ env.epn }}'
+
       - name: Commit and push changes
         run: |
           ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
-          mkdir -p profiles; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi; g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
+          mkdir -p profiles metadata; [ ! -f profiles/repo_name ] && echo "${{ env.github_repo }}" > profiles/repo_name; [ ! -f profiles/eapi ] && echo "8" > profiles/eapi; [ ! -f metadata/layout.conf ] && wget -qO - https://raw.githubusercontent.com/gentoo/gentoo/master/metadata/layout.conf > metadata/layout.conf || true; if ! grep -q "^cache-formats" metadata/layout.conf; then echo "cache-formats = md5-dict" >> metadata/layout.conf; else echo "::warning title=Layout.conf check::cache-formats is already defined in layout.conf, skipping generation."; fi; g2 cache generate "${{ env.ecn }}/${{ env.epn }}"
           git add "./${ebuild_dir}"
           if git commit -m "Add ebuilds for new ${{ env.epn }} releases tag ${generated_tag}"; then
             git pull --rebase &&
