Wrong file

diff --git a/.github/workflows/dev-go-goreleaser-bin-update.yaml b/.github/workflows/dev-go-goreleaser-bin-update.yaml
--- a/.github/workflows/dev-go-goreleaser-bin-update.yaml
+++ b/.github/workflows/dev-go-goreleaser-bin-update.yaml
@@ -1,11 +1,13 @@
-name: dev-go/goreleaser-bin Update
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github Binary Release todo.config 2024-08-15 13:49:39.146382751 +1000 AEST m=+0.001627385
+
+name: dev-go/goreleaser-bin update
 
 permissions:
   contents: write
 
 on:
   schedule:
-    - cron: '35 1 * * *'
+    - cron: '45 17 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -16,14 +18,25 @@ concurrency:
   cancel-in-progress: false
 
 env:
-  ebuild_category: dev-go
-  ebuild_name: goreleaser-bin
+  ecn: dev-go
+  epn: goreleaser-bin
+  description: "Deliver Go binaries as fast and easily as possible"
+  homepage: "https://goreleaser.com"
   github_owner: goreleaser
   github_repo: goreleaser
-  description: " Deliver Go binaries as fast and easily as possible."
-  PFN: "goreleaser"
-  EFN: "goreleaser"
-  homepage: "https://goreleaser.com/"
+  keywords: ~amd64 ~arm ~arm64 ~ppc64 ~x86
+  workflow_filename: dev-go-goreleaser-bin-update.yaml
+  goreleaser_binary_installed_name: 'goreleaser'
+  goreleaser_binary_archived_name_amd64: 'goreleaser'
+  goreleaser_release_name_amd64: 'goreleaser_Linux_x86_64.tar.gz'
+  goreleaser_binary_archived_name_arm: 'goreleaser'
+  goreleaser_release_name_arm: 'goreleaser_Linux_armv7.tar.gz'
+  goreleaser_binary_archived_name_arm64: 'goreleaser'
+  goreleaser_release_name_arm64: 'goreleaser_Linux_arm64.tar.gz'
+  goreleaser_binary_archived_name_ppc64: 'goreleaser'
+  goreleaser_release_name_ppc64: 'goreleaser_Linux_ppc64.tar.gz'
+  goreleaser_binary_archived_name_x86: 'goreleaser'
+  goreleaser_release_name_x86: 'goreleaser_Linux_i386.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -50,75 +63,131 @@ jobs:
       - name: Process each release
         id: process_releases
         run: |
-          ebuild_dir="./${ebuild_category}/${ebuild_name}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{env.github_owner}}/${{env.github_repo}}/releases | jq -r '.[].tag_name')
-          
-          for tag in ${tags}; do
-            version=${tag#v}
+          declare -A releaseTypes=()
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
+          for tag in $tags; do
+            version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-              echo "$tag == $version So no prefix v";
-              continue
+                echo "$version == $tag so there is no v removed skipping"
+                continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "$tag / $version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue;
             fi
-            ebuild_file="${ebuild_dir}/${ebuild_name}-${version}.ebuild"
+            releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
+            if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
+                releaseTypes[${releaseType:=release}]="$version"
+            else
+                echo "Already have a newier ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
+                continue
+            fi
+            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
-              # Create ebuild script
+
               {
-                echo "# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/dev-go-goreleaser-bin-update.yaml"
-                echo "EAPI=8"
-                echo "DESCRIPTION=\"$description\""
-                echo "HOMEPAGE=\"$homepage\""
-                echo 'IUSE="man"'
-                echo 'SRC_URI="'
-                echo "  amd64? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_x86_64.tar.gz -> \${P}.amd64.tar.gz )"
-                echo "  arm? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_armv7.tar.gz -> \${P}.arm.tar.gz )"
-                echo "  arm64? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_arm64.tar.gz -> \${P}.arm64.tar.gz )"
-                echo "  x86? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_i386.tar.gz -> \${P}.x86.tar.gz )"
-                echo '" '
-                echo "LICENSE=\"MIT\""
-                echo "SLOT=\"0\""
-                echo 'KEYWORDS="~amd64 ~arm ~arm64 ~x86"'
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
+                echo 'EAPI=8'
+                echo "DESCRIPTION=\"${{ env.description }}\""
+                echo "HOMEPAGE=\"${{ env.homepage }}\""
+                echo 'LICENSE="MIT"'
+                echo 'SLOT="0"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=" man doc bash fish zsh"'
+                echo 'REQUIRED_USE=""'
+                echo 'DEPEND=""'
                 echo 'RDEPEND=""'
-                echo 'DEPEND="${RDEPEND}"'
-                echo "S=\"\${WORKDIR}\""
-                echo 'RESTRICT="strip"'
-                echo ""
-                echo "src_install() {"
-                echo "    exeinto /opt/bin"
-                echo "    doexe ${EFN}"
-                echo "    dodoc LICENSE.md README.md"
-                echo "    insinto /usr/share/bash-completion/completions"
-                echo "    doins completions/goreleaser.bash"
-                echo "    insinto /usr/share/fish/vendor_completions.d"
-                echo "    doins completions/goreleaser.fish"
-                echo "    insinto /usr/share/zsh/site-functions"
-                echo "    doins completions/goreleaser.zsh"
-                echo "    if use man; then"
-                echo "      gzip -d manpages/goreleaser.1.gz"
-                echo "      doman manpages/goreleaser.1"
-                echo "    fi"
-                echo "}"
+                echo 'S="${WORKDIR}"'
+                echo ''
+                echo ''
+                echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_x86_64.tar.gz -> \${P}-goreleaser_Linux_x86_64.tar.gz  )  "
+                echo "  arm? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_armv7.tar.gz -> \${P}-goreleaser_Linux_armv7.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_arm64.tar.gz -> \${P}-goreleaser_Linux_arm64.tar.gz  )  "
+                echo "  ppc64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_ppc64.tar.gz -> \${P}-goreleaser_Linux_ppc64.tar.gz  )  "
+                echo "  x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_i386.tar.gz -> \${P}-goreleaser_Linux_i386.tar.gz  )  "
+                echo '"'
+                echo ''
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_armv7.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use ppc64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_ppc64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-goreleaser_Linux_i386.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use man; then'
+                echo '    gzip -d "manpages/goreleaser.1.gz" || die "Failed to decompress manual page goreleaser.1"'
+                echo '  fi'
+                echo '}'
+                echo ''
+                echo 'src_install() {'
+                echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_amd64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_arm }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_arm64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use ppc64; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_ppc64 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.goreleaser_binary_archived_name_x86 }}" "${{ env.goreleaser_binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use bash; then'
+                echo '    insinto "/usr/share/bash-completion/completions"
+                echo '    newins "completions/goreleaser.bash" "goreleaser.bash" || die "Failed to bash completion file"'
+                echo '  fi'
+                echo '  if use fish; then'
+                echo '    insinto "/usr/share/fish/vendor_completions.d"
+                echo '    newins "completions/goreleaser.fish" "goreleaser.fish" || die "Failed to bash completion file"'
+                echo '  fi'
+                echo '  if use zsh; then'
+                echo '    insinto "/usr/share/zsh/site-functions"
+                echo '    newins "completions/goreleaser.zsh" "goreleaser.zsh" || die "Failed to bash completion file"'
+                echo '  fi'
+                echo '  if use man; then'
+                echo '    newman "manpages/goreleaser.1" "goreleaser.1" || die "Failed to install manual page goreleaser.1"'
+                echo '  fi'
+                echo '  if use doc; then'
+                echo '    newdoc "LICENSE.md" "LICENSE.md" || die "Failed to install document LICENSE.md"'
+                echo '    newdoc "README.md" "README.md" || die "Failed to install document README.md"'
+                echo '  fi'
+                echo '}'
                 echo ""
               } > $ebuild_file
 
-              # Generate the manifest for the new ebuild
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_x86_64.tar.gz" "${ebuild_name}-${version}.amd64.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_armv7.tar.gz" "${ebuild_name}-${version}.arm.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_arm64.tar.gz" "${ebuild_name}-${version}.arm64.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_i386.tar.gz" "${ebuild_name}-${version}.x86.tar.gz" "${ebuild_dir}/Manifest"
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_armv7.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_armv7.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_ppc64.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_ppc64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/goreleaser_Linux_i386.tar.gz" "${{ env.epn }}-${version}-goreleaser_Linux_i386.tar.gz" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
-            break
           done
 
       - name: Commit and push changes
         run: |
-          ebuild_dir="./${ebuild_category}/${ebuild_name}"
-          git add "./${ebuild_dir}"
-          git commit -m "Add ebuilds for new ${ebuild_name} releases" && 
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
+          git add ./${ebuild_dir}
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag
