I broke the echos

diff --git a/.github/workflows/dev-ml-ollama-bin-update.yaml b/.github/workflows/dev-ml-ollama-bin-update.yaml
--- a/.github/workflows/dev-ml-ollama-bin-update.yaml
+++ b/.github/workflows/dev-ml-ollama-bin-update.yaml
@@ -94,9 +94,9 @@ jobs:
                 echo "src_install() {"
                 echo '  exeinto /opt/Ollama'
                 echo '  if use amd64; then'
-                echo '    newexe "${DISTDIR}/${P}.amd64" "ollama"' || die "Failed to install binary"'
+                echo '    newexe "${DISTDIR}/${P}.amd64" "ollama" || die "Failed to install binary"'
                 echo '  elif use arm64; then'
-                echo '    newexe "${DISTDIR}/${P}.arm64" "ollama"' || die "Failed to install binary"'
+                echo '    newexe "${DISTDIR}/${P}.arm64" "ollama" || die "Failed to install binary"'
                 echo '  fi'
                 echo '  dosym /opt/Ollama/ollama /opt/bin/ollama'
                 echo "}"
