fix(net-misc/termscp-bin): resolve g2-lint header and formatting issues
Add standard Gentoo copyright and GPL-2 header to termscp-bin-1.2.0.ebuild
and format the ebuild to adhere to g2 lint policies:
- Use tabs for indentation.
- Wrap long lines (SRC_URI, unpack) within 80 characters.
- Use URI helper variable to keep SRC_URI concise and parseable.

Update the ebuild generator block in net-misc-termscp-bin-update.yaml
so that future automated updates produce clean, compliant ebuilds.

diff --git a/.github/workflows/net-misc-termscp-bin-update.yaml b/.github/workflows/net-misc-termscp-bin-update.yaml
--- a/.github/workflows/net-misc-termscp-bin-update.yaml
+++ b/.github/workflows/net-misc-termscp-bin-update.yaml
@@ -99,54 +99,60 @@ jobs:
 
               # shellcheck disable=SC2016
               {
-                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
+                echo '# Copyright 2026 Gentoo Authors'
+                echo '# Distributed under the terms of the GNU General Public License v2'
+                echo ''
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/'
+                echo '#   .github/workflows/${{ env.workflow_filename }}'
                 echo 'EAPI=8'
                 echo "DESCRIPTION=\"${{ env.description }}\""
                 echo "HOMEPAGE=\"${{ env.homepage }}\""
+                echo ''
+                echo "URI=\"github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}\""
                 echo 'SRC_URI="'
-                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/termscp-${tag}-x86_64-unknown-linux-musl.tar.gz -> \${P}-termscp-${tag}-x86_64-unknown-linux-musl.tar.gz  )  "
-                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/v\${PV}/termscp-${tag}-aarch64-unknown-linux-musl.tar.gz -> \${P}-termscp-${tag}-aarch64-unknown-linux-musl.tar.gz  )  "
+                printf '\t%s\n' 'amd64? ('
+                printf '\t\t%s\n' "https://\${URI}/termscp-v\${PV}-x86_64-unknown-linux-musl.tar.gz"
+                printf '\t\t\t%s\n' "-> \${P}-termscp-v\${PV}-x86_64-unknown-linux-musl.tar.gz"
+                printf '\t%s\n' ')'
+                printf '\t%s\n' 'arm64? ('
+                printf '\t\t%s\n' "https://\${URI}/termscp-v\${PV}-aarch64-unknown-linux-musl.tar.gz"
+                printf '\t\t\t%s\n' "-> \${P}-termscp-v\${PV}-aarch64-unknown-linux-musl.tar.gz"
+                printf '\t%s\n' ')'
                 echo '"'
                 echo 'LICENSE="MIT"'
                 echo 'SLOT="0"'
                 echo 'KEYWORDS="${{ env.keywords }}"'
-                echo -n 'IUSE="'
-                echo -n ''
-                echo -n ''
-                echo -n ''
-                echo -n ''
-                echo '"'
+                echo 'IUSE=""'
                 echo ''
-                echo -n 'REQUIRED_USE="'
-                echo -n ''
-                echo '"'
+                echo 'REQUIRED_USE=""'
                 echo ''
-                echo -n 'RDEPEND="'
-                echo -n 'net-fs/samba '
-                echo -n ''
-                echo '"'
+                echo 'RDEPEND="net-fs/samba "'
                 echo ''
                 echo 'S="${WORKDIR}"'
                 echo ''
                 echo 'src_unpack() {'
-                echo '  if use amd64; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-termscp-${tag}-x86_64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
-                echo '  fi'
-                echo '  if use arm64; then'
-                echo "    unpack \"\${DISTDIR}/\${P}-termscp-${tag}-aarch64-unknown-linux-musl.tar.gz\" || die \"Can't unpack archive file\""
-                echo '  fi'
+                printf '\t%s\n' 'if use amd64; then'
+                printf '\t\t%s\n' 'unpack \'
+                printf '\t\t\t%s\n' "\"${DISTDIR}/\${P}-termscp-v\${PV}-x86_64-unknown-linux-musl.tar.gz\" \\"
+                printf '\t\t\t%s\n' '|| die "Can'\''t unpack archive file"'
+                printf '\t%s\n' 'fi'
+                printf '\t%s\n' 'if use arm64; then'
+                printf '\t\t%s\n' 'unpack \'
+                printf '\t\t\t%s\n' "\"${DISTDIR}/\${P}-termscp-v\${PV}-aarch64-unknown-linux-musl.tar.gz\" \\"
+                printf '\t\t\t%s\n' '|| die "Can'\''t unpack archive file"'
+                printf '\t%s\n' 'fi'
                 echo '}'
                 echo ''
                 echo 'src_install() {'
-                echo '  exeinto /opt/bin'
-                echo '  if use amd64; then'
-                echo '    newexe "${{ env.termscp_binary_archived_name_amd64 }}" "${{ env.termscp_binary_installed_name }}" || die "Failed to install Binary"'
-                echo '  fi'
-                echo '  if use arm64; then'
-                echo '    newexe "${{ env.termscp_binary_archived_name_arm64 }}" "${{ env.termscp_binary_installed_name }}" || die "Failed to install Binary"'
-                echo '  fi'
+                printf '\t%s\n' 'exeinto /opt/bin'
+                printf '\t%s\n' 'if use amd64; then'
+                printf '\t\t%s\n' 'newexe "${{ env.termscp_binary_archived_name_amd64 }}" "${{ env.termscp_binary_installed_name }}" || die "Failed to install Binary"'
+                printf '\t%s\n' 'fi'
+                printf '\t%s\n' 'if use arm64; then'
+                printf '\t\t%s\n' 'newexe "${{ env.termscp_binary_archived_name_arm64 }}" "${{ env.termscp_binary_installed_name }}" || die "Failed to install Binary"'
+                printf '\t%s\n' 'fi'
                 echo '}'
-              } > $ebuild_file
+              } > "$ebuild_file"
 
               # Manifest generation
 
