There it is!

diff --git a/.github/workflows/net-misc-rustdesk-appimage-update.yaml b/.github/workflows/net-misc-rustdesk-appimage-update.yaml
--- a/.github/workflows/net-misc-rustdesk-appimage-update.yaml
+++ b/.github/workflows/net-misc-rustdesk-appimage-update.yaml
@@ -69,7 +69,7 @@ jobs:
                 echo ''
                 echo "src_unpack() {"
                 echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\"  || die \"Can't copy archive file\""
-                echo "  chmod a+x "\${A}\"  || die \"Can't chmod archive file\""
+                echo "  chmod a+x \"\${A}\"  || die \"Can't chmod archive file\""
                 echo "  \"./\${A}\" --appimage-extract rustdesk.desktop || die \"Can't extract .desktop from appimage\""
                 echo "  \"./\${A}\" --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
                 echo "}"
