Slack dump now updated.

diff --git a/.github/workflows/net-im-slackdump-bin-update.yaml b/.github/workflows/net-im-slackdump-bin-update.yaml
--- a/.github/workflows/net-im-slackdump-bin-update.yaml
+++ b/.github/workflows/net-im-slackdump-bin-update.yaml
@@ -1,11 +1,13 @@
-name: net-im/slackdump-bin Update
+# Generated using: https://github.com/arran4/arrans_overlay_workflow_builder Github Binary Release todo.config 2024-08-15 13:49:39.146382751 +1000 AEST m=+0.001627385
+
+name: net-im/slackdump-bin update
 
 permissions:
   contents: write
 
 on:
   schedule:
-    - cron: '40 1 * * *'
+    - cron: '4 16 * * *'
   workflow_dispatch:
   push:
     paths:
@@ -16,15 +18,21 @@ concurrency:
   cancel-in-progress: false
 
 env:
-  ebuild_category: net-im
-  ebuild_name: slackdump-bin
+  ecn: net-im
+  epn: slackdump-bin
+  description: "Save or export your private and public Slack messages, threads, files, and users locally without admin privileges."
+  homepage: ""
   github_owner: rusq
   github_repo: slackdump
-  description: "Save or export your private and public Slack messages, threads, files, and users locally without admin privileges."
-  PFN: "slackdump"
-  EFN: "slackdump"
-  homepage: "https://github.com/rusq/slackdump"
-  license: GPL-3.0
+  keywords: ~amd64 ~arm64 ~x86
+  workflow_filename: net-im-slackdump-bin-update.yaml
+  binary_installed_name: 'slackdump'
+  binary_archived_name_amd64: 'slackdump'
+  release_name_amd64: 'slackdump_Linux_x86_64.tar.gz'
+  binary_archived_name_arm64: 'slackdump'
+  release_name_arm64: 'slackdump_Linux_arm64.tar.gz'
+  binary_archived_name_x86: 'slackdump'
+  release_name_x86: 'slackdump_Linux_i386.tar.gz'
 
 jobs:
   check-and-create-ebuild:
@@ -40,77 +48,105 @@ jobs:
 
       - name: Install required tools
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget jq coreutils
-          url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
-          echo "$url"
-          wget "${url}" -O /tmp/g2.deb
-          sudo dpkg -i /tmp/g2.deb
-          rm /tmp/g2.deb
+            sudo apt-get update
+            sudo apt-get install -y wget jq coreutils
+            url="$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/arran4/g2/releases/latest | jq -r '.assets[].browser_download_url | select(endswith("_linux_amd64.deb"))')"
+            echo "$url"
+            wget "${url}" -O /tmp/g2.deb
+            sudo dpkg -i /tmp/g2.deb
+            rm /tmp/g2.deb
 
       - name: Process each release
         id: process_releases
         run: |
-          ebuild_dir="./${ebuild_category}/${ebuild_name}"
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
           mkdir -p $ebuild_dir
-          tags=$(curl -s --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{env.github_owner}}/${{env.github_repo}}/releases | jq -r '.[].tag_name')
-          
-          for tag in ${tags}; do
-            version=${tag#v}
+          declare -A releaseTypes=()
+          tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[].tag_name')
+          for tag in $tags; do
+            version="${tag#v}"
             if [ "${version}" = "${tag}" ]; then
-              echo "$version == $tag so there is no V removed"
-              continue
+                echo "$version == $tag so there is no v removed skipping"
+                continue
             fi
-            if ! echo "$version" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
-              echo "$version doesn't match regexp";
-              continue; 
+            originalVersion="${version}"
+            version="$(echo "${version}" | sed 's/^\([0-9]\+\(\.[0-9]\+\)*\)\(-r[0-9]*\)\?\([-_]\(alpha\|beta\|rc\|p\)[0-9]*\)$/\1_\5\3/')"
+            if ! echo "${version}" | egrep '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
+                echo "tag / $version doesn't match regexp";
+                continue;
             fi
-            ebuild_file="${ebuild_dir}/${ebuild_name}-${version}.ebuild"
+            releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
+            if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
+                releaseTypes[${releaseType:=release}]="$version"
+            else
+                echo "Already have a newier ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
+                continue
+            fi
+            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
             if [ ! -f "$ebuild_file" ]; then
-              # Create ebuild script
+
               {
-                echo "# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/net-im-slackdump-bin-update.yaml"
-                echo "EAPI=8"
-                echo "DESCRIPTION=\"$description\""
-                echo "HOMEPAGE=\"$homepage\""
-                echo 'IUSE="man"'
-                echo 'SRC_URI="'
-                echo "  amd64? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_x86_64.tar.gz -> \${P}.amd64.tar.gz )"
-                echo "  arm64? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_arm64.tar.gz -> \${P}.arm64.tar.gz )"
-                echo "  x86? ( https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v\${PV}/${PFN}_Linux_i386.tar.gz -> \${P}.x86.tar.gz )"
-                echo '" '
-                echo "LICENSE=\"${{env.license}}\""
-                echo "SLOT=\"0\""
-                echo 'KEYWORDS="~amd64 ~arm64 ~x86"'
+                echo '# Generated via: https://github.com/arran4/arrans_overlay/blob/main/.github/workflows/${{ env.workflow_filename }}'
+                echo 'EAPI=8'
+                echo "DESCRIPTION=\"${{ env.description }}\""
+                echo "HOMEPAGE=\"${{ env.homepage }}\""
+                echo 'LICENSE="MIT"'
+                echo 'SLOT="0"'
+                echo 'KEYWORDS="${{ env.keywords }}"'
+                echo 'IUSE=""'
+                echo 'REQUIRED_USE=""'
+                echo 'DEPEND=""'
                 echo 'RDEPEND=""'
-                echo 'DEPEND="${RDEPEND}"'
-                echo "S=\"\${WORKDIR}\""
-                echo 'RESTRICT="strip"'
-                echo ""
-                echo "src_install() {"
-                echo "    exeinto /opt/bin"
-                echo "    doexe ${EFN}"
-                echo "    dodoc LICENSE README.rst"
-                echo "    if use man; then"
-                echo "      doman slackdump.1"
-                echo "    fi"
-                echo "}"
+                echo 'S="${WORKDIR}"'
+                echo ''
+                echo ''
+                echo 'SRC_URI="'
+                echo "  amd64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_x86_64.tar.gz -> \${P}-slackdump_Linux_x86_64.tar.gz  )  "
+                echo "  arm64? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_arm64.tar.gz -> \${P}-slackdump_Linux_arm64.tar.gz  )  "
+                echo "  x86? (  https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_i386.tar.gz -> \${P}-slackdump_Linux_i386.tar.gz  )  "
+                echo '"'
+                echo ''
+                echo 'src_unpack() {'
+                echo '  if use amd64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_x86_64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_arm64.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '  if use x86; then'
+                echo "    unpack \"\${DISTDIR}/\${P}-slackdump_Linux_i386.tar.gz\" || die \"Can't unpack archive file\""
+                echo '  fi'
+                echo '}'
+                echo ''
+                echo 'src_install() {'
+                echo '  exeinto /opt/bin'
+                echo '  if use amd64; then'
+                echo '    newexe "${{ env.binary_archived_name_amd64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use arm64; then'
+                echo '    newexe "${{ env.binary_archived_name_arm64 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '  if use x86; then'
+                echo '    newexe "${{ env.binary_archived_name_x86 }}" "${{ env.binary_installed_name }}" || die "Failed to install Binary"'
+                echo '  fi'
+                echo '}'
                 echo ""
               } > $ebuild_file
 
-              # Generate the manifest for the new ebuild
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_x86_64.tar.gz" "${ebuild_name}-${version}.amd64.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_arm64.tar.gz" "${ebuild_name}-${version}.arm64.tar.gz" "${ebuild_dir}/Manifest"
-              g2 manifest upsert-from-url "https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/${tag}/${PFN}_Linux_i386.tar.gz" "${ebuild_name}-${version}.x86.tar.gz" "${ebuild_dir}/Manifest"
+              # Manifest generation
+
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_x86_64.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_x86_64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_arm64.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_arm64.tar.gz" "${ebuild_dir}/Manifest"
+              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/releases/download/${tag}/slackdump_Linux_i386.tar.gz" "${{ env.epn }}-${version}-slackdump_Linux_i386.tar.gz" "${ebuild_dir}/Manifest"
+              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
             fi
-            break
           done
 
       - name: Commit and push changes
         run: |
-          ebuild_dir="./${ebuild_category}/${ebuild_name}"
-          git add "./${ebuild_dir}"
-          git commit -m "Add ebuilds for new ${ebuild_name} releases" && 
+          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
+          git add ./${ebuild_dir}
+          git commit -m "Add ebuilds for new ${{ env.epn }} releases" &&
           git pull --rebase &&
           git push || true
-        if: steps.process_releases.conclusion == 'success'
+        if: steps.process_releases.outputs.generated_tag
