I've got to stop trying to rely on llm for pattern propagation

diff --git a/.github/workflows/net-im-caprine-appimage-update.yaml b/.github/workflows/net-im-caprine-appimage-update.yaml
--- a/.github/workflows/net-im-caprine-appimage-update.yaml
+++ b/.github/workflows/net-im-caprine-appimage-update.yaml
@@ -65,17 +65,17 @@ jobs:
                 echo 'S="${WORKDIR}"'
                 echo 'RESTRICT="strip"'
                 echo ''
-                echo 'SRC_URI="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${PV}/Caprine-${PV}.AppImage -> ${P}.AppImage"'
+                echo 'SRC_URI="https://github.com/${{env.github_owner}}/${{env.github_repo}}/releases/download/v${PV}/Caprine-${PV}.AppImage -> ${P}.AppImage"'
                 echo ''
                 echo 'src_unpack() {'
                 echo '  cp "${DISTDIR}/${A}" "${A}" || die "Can't copy archive file"'
                 echo '  chmod a+x "${A}" || die "Can't chmod archive file"'
-                echo '  "./${A}" --appimage-extract ${DESKTOP_FILE} || die "Can't extract .desktop from appimage"'
+                echo '  "./${A}" --appimage-extract ${{env.desktop_file}} || die "Can't extract .desktop from appimage"'
                 echo '  "./${A}" --appimage-extract usr/share/icons || die "Can't extract icons from app image"'
                 echo '}'
                 echo ''
                 echo 'src_prepare() {'
-                echo '  sed -i 's:^Exec=.*:Exec=/opt/bin/caprine:' squashfs-root/${DESKTOP_FILE}'
+                echo '  sed -i 's:^Exec=.*:Exec=/opt/bin/caprine:' squashfs-root/${{env.desktop_file}}'
                 echo '  eapply_user'
                 echo '}'
                 echo ''
@@ -83,7 +83,7 @@ jobs:
                 echo '  exeinto /opt/bin'
                 echo '  doexe squashfs-root/AppRun || die "Failed to install AppRun"'
                 echo '  insinto /usr/share/applications'
-                echo '  doins squashfs-root/${DESKTOP_FILE}'
+                echo '  doins squashfs-root/${{env.desktop_file}}'
                 echo '  insinto /usr/share/icons'
                 echo '  doins -r squashfs-root/usr/share/icons/*'
                 echo '}'
